'skript syntax'

import * as Blockly from 'blockly/core'
import type { SkriptType } from './Types'
import { createTypeBlock } from './Types'

export const AttributeTypes: SkriptType = {
  name: 'attribute_type',
  type: 'attributetype',
  options: [
    'generic armor',
    'generic armor toughness',
    'generic attack damage',
    'generic attack knockback',
    'generic attack speed',
    'generic burning time',
    'generic explosion knockback resistance',
    'generic flying speed',
    'generic follow range',
    'generic gravity',
    'generic jump strength',
    'generic knockback resistance',
    'generic luck',
    'generic max absorption',
    'generic max health',
    'generic movement efficiency',
    'generic movement speed',
    'generic oxygen bonus',
    'generic safe fall distance',
    'generic fall damage multiplier',
    'generic scale',
    'generic step height',
    'generic water movement efficiency',
    'horse jump strength',
    'player block break speed',
    'player block interaction range',
    'player entity interaction range',
    'player mining efficiency',
    'player sneaking speed',
    'player submerged mining speed',
    'player sweeping damage ratio',
    'zombie spawn reinforcements',
    'armor',
    'armor toughness',
    'attack damage',
    'attack knockback',
    'attack speed',
    'burning time',
    'explosion knockback resistance',
    'flying speed',
    'follow range',
    'gravity',
    'jump strength',
    'knockback resistance',
    'luck',
    'max absorption',
    'max health',
    'movement efficiency',
    'movement speed',
    'oxygen bonus',
    'safe fall distance',
    'fall damage multiplier',
    'scale',
    'step height',
    'tempt range',
    'water movement efficiency',
    'block break speed',
    'block interaction range',
    'entity interaction range',
    'mining efficiency',
    'sneaking speed',
    'submerged mining speed',
    'sweeping damage ratio',
    'spawn reinforcements',
    'camera distance',
    'waypoint transmit range',
    'waypoint receive range',
  ],
}


export function register(): Blockly.utils.toolbox.BlockInfo {
  return createTypeBlock(AttributeTypes, 'Attribute', 0)
}