'skript syntax'

import * as Blockly from 'blockly/core'
import type { SkriptType } from './Types'
import { createTypeBlock } from './Types'

export const Biomes: SkriptType = {
  name: 'biome',
  type: 'biome',
  options: [
    'swamp',
    'swamp hills',
    'forest',
    'taiga',
    'desert',
    'plains',
    'nether',
    'the end',
    'ocean',
    'river',
    'mountains',
    'frozen ocean',
    'frozen river',
    'snowy tundra',
    'snowy mountains',
    'mushroom fields',
    'mushroom field shore',
    'beach',
    'desert hills',
    'wooded hills',
    'taiga hills',
    'mountain edge',
    'jungle',
    'jungle hills',
    'jungle edge',
    'deep ocean',
    'stone shore',
    'snowy beach',
    'birch forest',
    'birch forest hills',
    'dark forest',
    'snowy taiga',
    'snowy taiga hills',
    'giant tree taiga',
    'giant tree taiga hills',
    'wooded mountains',
    'savanna',
    'savanna plateau',
    'badlands',
    'wooded badlands plateau',
    'badlands plateau',
    'eroded badlands',
    'sunflower plains',
    'desert lakes',
    'flower forest',
    'taiga mountains',
    'swampland mountains',
    'ice spikes',
    'modified jungle',
    'modified jungle edge',
    'snowy taiga mountains',
    'shattered savanna',
    'shattered savanna plateau',
    'eroded badlands',
    'modified wooded badlands plateau',
    'modified badlands plateau',
    'tall birch forest',
    'tall birch hills',
    'dark forest hills',
    'giant spruce taiga',
    'gravelly mountains',
    'modified gravelly mountains',
    'giant spruce taiga hills',
    'the void',
    'small end islands',
    'end midlands',
    'end highlands',
    'end barrens',
    'warm ocean',
    'lukewarm ocean',
    'cold ocean',
    'deep warm ocean',
    'deep lukewarm ocean',
    'deep cold ocean',
    'deep frozen ocean',
    'bamboo jungle',
    'bamboo jungle hills',
    'nether wastes',
    'crimson forest',
    'soul sand valley',
    'warped forest',
    'basalt deltas',
    'custom',
    'dripstone caves',
    'lush caves',
    'meadow',
    'snowy slopes',
    'jagged peaks',
    'stony peaks',
    'frozen peaks',
    'grove',
    'old growth birch forest',
    'old growth pine taiga',
    'old growth spruce taiga',
    'snowy plains',
    'sparse jungle',
    'stony shore',
    'windswept hills',
    'windswept forest',
    'windswept gravelly hills',
    'windswept savanna',
    'wooded badlands',
    'mangrove swamp',
    'deep dark',
    'cherry grove',
    'pale garden',
  ],
}


export function register(): Blockly.utils.toolbox.BlockInfo {
  return createTypeBlock(Biomes, 'Biomes', 2133)
}