'skript syntax'

import * as Blockly from 'blockly/core'
import type { SkriptType } from './Types'
import { createTypeBlock } from './Types'

export const Entities: SkriptType = {
  name: 'entity',
  type: 'entity',
  options: [
    'axolotl',
    'lucy axolotl',
    'wild axolotl',
    'gold axolotl',
    'cyan axolotl',
    'blue axolotl',
    'bee',
    'no nectar bee',
    'nectar bee',
    'happy bee',
    'happy nectar bee',
    'happy no nectar bee',
    'angry bee',
    'angry no nectar bee',
    'angry nectar bee',
    'chest boat',
    'any chest boat',
    'oak chest boat',
    'spruce chest boat',
    'birch chest boat',
    'jungle chest boat',
    'acacia chest boat',
    'dark oak chest boat',
    'cherry chest boat',
    'mangrove chest boat',
    'bamboo chest raft',
    'pale oak chest boat',
    'boat',
    'any boat',
    'oak boat',
    'spruce boat',
    'birch boat',
    'jungle boat',
    'acacia boat',
    'dark oak boat',
    'mangrove boat',
    'bamboo raft',
    'cherry boat',
    'pale oak boat',
    'cat',
    'chicken',
    'cow',
    'creeper',
    'unpowered creeper',
    'powered creeper',
    'dropped item',
    'enderman',
    'falling block',
    'fox',
    'red fox',
    'snow fox',
    'cold frog',
    'frog',
    'temperate frog',
    'warm frog',
    'goat',
    'screaming goat',
    'quiet goat',
    'llama',
    'creamy llama',
    'white llama',
    'brown llama',
    'gray llama',
    'trader llama',
    'creamy trader llama',
    'white trader llama',
    'brown trader llama',
    'gray trader llama',
    'minecart',
    'regular minecart',
    'storage minecart',
    'powered minecart',
    'hopper minecart',
    'explosive minecart',
    'spawner minecart',
    'command minecart',
    'mooshroom',
    'red mooshroom',
    'brown mooshroom',
    'panda',
    'parrot',
    'red parrot',
    'blue parrot',
    'green parrot',
    'cyan parrot',
    'gray parrot',
    'pig',
    'saddled pig',
    'unsaddled pig',
    'rabbit',
    'brown rabbit',
    'black and white rabbit',
    'white rabbit',
    'black rabbit',
    'gold rabbit',
    'salt and pepper rabbit',
    'killer rabbit',
    'salmon',
    'any salmon',
    'large salmon',
    'medium salmon',
    'small salmon',
    'sheep',
    'unsheared sheep',
    'sheared sheep',
    'strider',
    'warm strider',
    'shivering strider',
    'thrown potion',
    'tropical fish',
    'kob',
    'sunstreak',
    'snooper',
    'dasher',
    'brinely',
    'spotty',
    'flopper',
    'stripey',
    'glitter',
    'blockfish',
    'betty',
    'clayfish',
    'villager',
    'unemployed',
    'armorer',
    'cartographer',
    'cleric',
    'fisherman',
    'fletcher',
    'leatherworker',
    'mason',
    'shepherd',
    'toolsmith',
    'weaponsmith',
    'farmer',
    'librarian',
    'butcher',
    'nitwit',
    'wolf',
    'tamed wolf',
    'wild wolf',
    'angry wolf',
    'peaceful wolf',
    'experience orb',
    'zombie villager',
    'zombie normal',
    'zombie farmer',
    'zombie librarian',
    'zombie butcher',
    'zombie nitwit',
    'zombie armorer',
    'zombie cartographer',
    'zombie cleric',
    'zombie fisherman',
    'zombie fletcher',
    'zombie leatherworker',
    'zombie mason',
    'zombie shepherd',
    'zombie toolsmith',
    'zombie weaponsmith',
    'display',
    'block display',
    'item display',
    'text display',
    'zombie',
    'skeleton',
    'tnt',
    'spider',
    'player',
    'lightning bolt',
    'giant',
    'ghast',
    'fish hook',
    'fireball',
    'dragon fireball',
    'small fireball',
    'large fireball',
    'ender crystal',
    'ender dragon',
    'ender pearl',
    'egg',
    'cave spider',
    'arrow',
    'squid',
    'snowball',
    'snow golem',
    'slime',
    'magma cube',
    'ender eye',
    'blaze',
    'zombie pigman',
    'bottle of enchanting',
    'iron golem',
    'ocelot',
    'wither',
    'wither skeleton',
    'wither skull',
    'firework',
    'witch',
    'bat',
    'item frame',
    'painting',
    'horse',
    'donkey',
    'mule',
    'undead horse',
    'skeleton horse',
    'leash hitch',
    'elder guardian',
    'normal guardian',
    'armor stand',
    'endermite',
    'silverfish',
    'tipped arrow',
    'area effect cloud',
    'shulker',
    'shulker bullet',
    'spectral arrow',
    'husk',
    'stray',
    'polar bear',
    'llama spit',
    'vindicator',
    'vex',
    'evoker',
    'evoker fangs',
    'illusioner',
    'trident',
    'cod',
    'puffer fish',
    'turtle',
    'drowned',
    'dolphin',
    'phantom',
    'pillager',
    'ravager',
    'wandering trader',
    'piglin',
    'hoglin',
    'zoglin',
    'piglin brute',
    'glow squid',
    'marker',
    'glow item frame',
    'allay',
    'tadpole',
    'warden',
    'camel',
    'sniffer',
    'interaction',
    'breeze',
    'wind charge',
    'armadillo',
    'bogged',
    'creaking',
    'happy ghast',
    'copper golem',
    'mannequin',
    'nautilus',
    'zombie nautilus',
    'any nautilus',
    'camel husk',
    'parched',
    'human',
    'damageable',
    'monster',
    'mob',
    'creature',
    'animal',
    'tameable',
    'fish',
    'golem',
    'projectile',
    'living entity',
    'entity',
    'chested horse',
    'any horse',
    'guardian',
    'water mob',
    'any fireball',
    'illager',
    'spellcaster',
    'raider',
    'enemy',
  ],
}

export const BabyEntities: SkriptType = {
  name: 'baby_entity',
  type: 'entity',
  options: [
    'baby axolotl',
    'baby lucy axolotl',
    'baby wild axolotl',
    'baby gold axolotl',
    'baby cyan axolotl',
    'baby blue axolotl',
    'baby bee',
    'baby no nectar bee',
    'baby nectar bee',
    'baby happy bee',
    'baby happy nectar bee',
    'baby happy no nectar bee',
    'baby angry bee',
    'baby angry no nectar bee',
    'baby angry nectar bee',
    'baby cat',
    'baby chicken',
    'baby cow',
    'baby fox',
    'baby red fox',
    'baby snow fox',
    'baby cold frog',
    'baby frog',
    'baby temperate frog',
    'baby warm frog',
    'baby goat',
    'baby screaming goat',
    'baby quiet goat',
    'baby llama',
    'baby creamy llama',
    'baby white llama',
    'baby brown llama',
    'baby gray llama',
    'baby trader llama',
    'baby creamy trader llama',
    'baby white trader llama',
    'baby brown trader llama',
    'baby gray trader llama',
    'baby mooshroom',
    'baby red mooshroom',
    'baby brown mooshroom',
    'baby panda',
    'baby pig',
    'baby rabbit',
    'baby brown rabbit',
    'baby black and white rabbit',
    'baby white rabbit',
    'baby black rabbit',
    'baby gold rabbit',
    'baby salt and pepper rabbit',
    'baby killer rabbit',
    'baby sheep',
    'baby unsheared sheep',
    'baby sheared sheep',
    'baby strider',
    'baby warm strider',
    'baby shivering strider',
    'baby villager',
    'baby unemployed',
    'baby armorer',
    'baby cartographer',
    'baby cleric',
    'baby fisherman',
    'baby fletcher',
    'baby leatherworker',
    'baby mason',
    'baby shepherd',
    'baby toolsmith',
    'baby weaponsmith',
    'baby farmer',
    'baby librarian',
    'baby butcher',
    'baby nitwit',
    'baby wolf',
    'baby tamed wolf',
    'baby wild wolf',
    'baby angry wolf',
    'baby peaceful wolf',
    'baby zombie villager',
    'baby zombie normal',
    'baby zombie farmer',
    'baby zombie librarian',
    'baby zombie butcher',
    'baby zombie nitwit',
    'baby zombie armorer',
    'baby zombie cartographer',
    'baby zombie cleric',
    'baby zombie fisherman',
    'baby zombie fletcher',
    'baby zombie leatherworker',
    'baby zombie mason',
    'baby zombie shepherd',
    'baby zombie toolsmith',
    'baby zombie weaponsmith',
    'baby zombie',
    'baby squid',
    'baby zombie pigman',
    'baby ocelot',
    'baby bat',
    'baby horse',
    'baby donkey',
    'baby mule',
    'baby undead horse',
    'baby skeleton horse',
    'baby husk',
    'baby polar bear',
    'baby turtle',
    'baby drowned',
    'baby dolphin',
    'baby wandering trader',
    'baby piglin',
    'baby hoglin',
    'baby zoglin',
    'baby piglin brute',
    'baby glow squid',
    'baby armadillo',
    'baby happy ghast',
    'baby nautilus',
    'baby any nautilus',
    'baby creature',
    'baby living entity',
    'baby entity',
    'baby chested horse',
    'baby any horse',
  ],
}


export function register(): Blockly.utils.toolbox.BlockInfo {
  return createTypeBlock(Entities, 'Entities', 2145)
}