'skript syntax'

import * as Blockly from 'blockly/core'
import type { SkriptType } from './Types'
import { createTypeBlock } from './Types'

export const EntityEffects: SkriptType = {
  name: 'entity_effect',
  type: 'entityeffect',
  options: [
    'arrow particles',
    'rabbit jump',
    'reset spawner minecart delay',
    'death',
    'entity death',
    'egg break',
    'snowball break',
    'projectile crack',
    'fang attack',
    'hoglin attack',
    'iron golen attack',
    'ravager attack',
    'ravager roared',
    'warden attack',
    'zoglin attack',
    'entity attack',
    'wolf smoke',
    'wolf hearts',
    'taming failed',
    'taming succeeded',
    'trusting failed',
    'trusting succeeded',
    'wolf shake',
    'wolf shake stop',
    'tnt minecart ignite',
    'iron golem rose',
    'iron golem sheath',
    'villager heart',
    'villager angry',
    'villager happy',
    'witch magic',
    'zombie transform',
    'firework explode',
    'love hearts',
    'squid rotate',
    'entity poof',
    'shield block',
    'shield break',
    'armor stand hit',
    'dolphin fed',
    'ravager stunned',
    'villager splash',
    'player bad omen raid',
    'fox chew',
    'teleport ender',
    'break equipment main hand',
    'break equipment off hand',
    'break equipment helmet',
    'break equipment chestplate',
    'break equipment leggings',
    'break equipment boots',
    'break equipment saddle',
    'body break',
    'break equipment body',
    'honey block slide particles',
    'honey block fall particles',
    'swap hand items',
    'goat lower head',
    'goat raise head',
    'spawn death smoke',
    'warden tendril shake',
    'warden sonic attack',
    'sniffer dig',
    'armadillo peek',
    'shake',
    'hit',
    'hurt drown',
    'drown particles',
    'sheep eat',
    'sheep eat grass',
    'totem resurrect',
    'protected from death',
    'guardian target',
    'thorns hurt',
    'hurt',
    'hurt explosion',
    'hurt berry bush',
    'cat tame fail',
    'cat tame success',
  ],
}


export function register(): Blockly.utils.toolbox.BlockInfo {
  return createTypeBlock(EntityEffects, 'EntityEffects', 0)
}