import type { SkriptType } from './Types'

export const GameEffects: SkriptType = {
  name: 'game_effect',
  options: [
    'click1',
    'click2',
    'bow fire',
    'extinguish',
    'ghast shriek',
    'ghast shoot',
    'blaze shoot',
    'zombie chew wooden door',
    'zombie chew iron door',
    'zombie destroy door',
    'ender signal',
    'mobspawner flames',
    'brewing stand brew',
    'chorus flower grow',
    'chorus flower death',
    'portal travel',
    'endereye launch',
    'firework shoot',
    'dragon breath',
    'anvil break',
    'anvil use',
    'anvil land',
    'enderdragon shoot',
    'enderdragon growl',
    'wither break block',
    'wither shoot',
    'zombie infect',
    'zombie converted villager',
    'zombie converted to drowned',
    'zombie converts to drowned',
    'husk converted to zombie',
    'husk converts to zombie',
    'skeleton converted to stray',
    'bat takeoff',
    'end gateway spawn',
    'phantom bite',
    'phantom bites',
    'grindstone use',
    'grindstone used',
    'book page turn',
    'book page turned',
    'smithing table use',
    'pointed dripstone drip lava into cauldron',
    'pointed dripstone drip water into cauldron',
    'dripping dripstone',
    'lava interact',
    'lava converts block',
    'redstone torch burnout',
    'redstone torch burns out',
    'end portal frame fill',
    'ender eye placed',
    'ender dragon destroy block',
    'ender dragon destroys block',
    'sponge dry',
    'copper wax on',
    'copper wax off',
    'oxidised copper scrape',
    'wither spawned',
    'ender dragon death',
    'end portal created in overworld',
    'composter composts',
    'pointed dripstone land',
    'sound stop jukebox song',
    'crafter craft',
    'crafter fail',
    'particles egg crack',
    'gust dust',
    'trial spawner eject item',
    'vault eject item',
    'spawn cobweb',
    'sound with charge shot',
    'door toggle',
    'iron door toggle',
    'trapdoor toggle',
    'iron trapdoor toggle',
    'fence gate toggle',
    'door close',
    'iron door close',
    'trapdoor close',
    'iron trapdoor close',
    'fence gate close',
    'record play',
    'smoke',
    'step sound',
    'potion break',
    'instant potion break',
    'villager plant grow',
    'composter fill attempt',
    'bone meal use',
    'electric spark',
    'shoot white smoke',
    'bee growth',
    'turtle egg placement',
    'smash attack',
    'particles sculk charge',
    'particles sculk shriek',
    'particles and sound brush block complete',
    'trial spawner spawn',
    'trial spawner spawn mob at',
    'trial spawner detect player',
    'vault activate',
    'vault deactivate',
    'trial spawner detect player ominous',
    'trial spawner become ominous',
    'trial spawner spawn item',
  ],
}
