import type { SkriptType } from './Types'

export const InventoryTypes: SkriptType = {
  name: 'inventory_type',
  options: [
    'chest',
    'dispenser',
    'dropper',
    'furnace',
    'workbench',
    'crafting',
    'enchanting',
    'brewing',
    'player',
    'creative',
    'merchant',
    'ender chest',
    'anvil',
    'beacon',
    'hopper',
    'shulker box',
    'barrel',
    'blast furnace',
    'lectern',
    'smoker',
    'loom',
    'cartography',
    'grindstone',
    'stonecutter',
    'smithing',
    'composter',
    'chiseled bookshelf',
    'decorated pot',
    'crafter',
    'shelf',
    'jukebox',
    'smithing new',
  ],
}
