import { type SkriptType } from './Types.ts'

export const ItemTypes: SkriptType = {
  name: 'item',
  options: [
    'potion',
    'potion of water',
    'potion of thick',
    'potion of mundane',
    'potion of awkward',
    'potion of night vision',
    'potion of long night vision',
    'potion of invisibility',
    'potion of long invisibility',
    'potion of leaping',
    'potion of long leaping',
    'potion of strong leaping',
    'potion of fire resistance',
    'potion of long fire resistance',
    'potion of swiftness',
    'potion of extended swiftness',
    'potion of strong swiftness',
    'potion of slowness',
    'potion of long slowness',
    'potion of strong slowness',
    'potion of water breathing',
    'potion of long water breathing',
    'potion of instant health',
    'potion of strong instant health',
    'potion of instant harming',
    'potion of strong instant harming',
    'potion of poisoning',
    'potion of long poisoning',
    'potion of strong poisoning',
    'potion of regeneration',
    'potion of long regeneration',
    'potion of strong regeneration',
    'potion of strength',
    'potion of long strength',
    'potion of strong strength',
    'potion of weakness',
    'potion of long weakness',
    'potion of luck',
    'potion of turtle master',
    'potion of long turtle master',
    'potion of strong turtle master',
    'potion of slow falling',
    'potion of long slow falling',
    'potion of water',
    'potion of thick',
    'potion of mundane',
    'potion of awkward',
    'potion of night vision',
    'potion of long night vision',
    'potion of invisibility',
    'potion of long invisibility',
    'potion of leaping',
    'potion of long leaping',
    'potion of strong leaping',
    'potion of fire resistance',
    'potion of long fire resistance',
    'potion of swiftness',
    'potion of extended swiftness',
    'potion of strong swiftness',
    'potion of slowness',
    'potion of long slowness',
    'potion of strong slowness',
    'potion of water breathing',
    'potion of long water breathing',
    'potion of instant health',
    'potion of strong instant health',
    'potion of instant harming',
    'potion of strong instant harming',
    'potion of poisoning',
    'potion of long poisoning',
    'potion of strong poisoning',
    'potion of regeneration',
    'potion of long regeneration',
    'potion of strong regeneration',
    'potion of strength',
    'potion of long strength',
    'potion of strong strength',
    'potion of weakness',
    'potion of long weakness',
    'potion of luck',
    'potion of turtle master',
    'potion of long turtle master',
    'potion of strong turtle master',
    'potion of slow falling',
    'potion of long slow falling',
    'splash potion',
    'splash potion of water',
    'splash potion of thick',
    'splash potion of mundane',
    'splash potion of awkward',
    'splash potion of night vision',
    'splash potion of long night vision',
    'splash potion of invisibility',
    'splash potion of long invisibility',
    'splash potion of leaping',
    'splash potion of long leaping',
    'splash potion of strong leaping',
    'splash potion of fire resistance',
    'splash potion of long fire resistance',
    'splash potion of swiftness',
    'splash potion of extended swiftness',
    'splash potion of strong swiftness',
    'splash potion of slowness',
    'splash potion of long slowness',
    'splash potion of strong slowness',
    'splash potion of water breathing',
    'splash potion of long water breathing',
    'splash potion of instant health',
    'splash potion of strong instant health',
    'splash potion of instant harming',
    'splash potion of strong instant harming',
    'splash potion of poisoning',
    'splash potion of long poisoning',
    'splash potion of strong poisoning',
    'splash potion of regeneration',
    'splash potion of long regeneration',
    'splash potion of strong regeneration',
    'splash potion of strength',
    'splash potion of long strength',
    'splash potion of strong strength',
    'splash potion of weakness',
    'splash potion of long weakness',
    'splash potion of luck',
    'splash potion of turtle master',
    'splash potion of long turtle master',
    'splash potion of strong turtle master',
    'splash potion of slow falling',
    'splash potion of long slow falling',
    'splash potion of water',
    'splash potion of thick',
    'splash potion of mundane',
    'splash potion of awkward',
    'splash potion of night vision',
    'splash potion of long night vision',
    'splash potion of invisibility',
    'splash potion of long invisibility',
    'splash potion of leaping',
    'splash potion of long leaping',
    'splash potion of strong leaping',
    'splash potion of fire resistance',
    'splash potion of long fire resistance',
    'splash potion of swiftness',
    'splash potion of extended swiftness',
    'splash potion of strong swiftness',
    'splash potion of slowness',
    'splash potion of long slowness',
    'splash potion of strong slowness',
    'splash potion of water breathing',
    'splash potion of long water breathing',
    'splash potion of instant health',
    'splash potion of strong instant health',
    'splash potion of instant harming',
    'splash potion of strong instant harming',
    'splash potion of poisoning',
    'splash potion of long poisoning',
    'splash potion of strong poisoning',
    'splash potion of regeneration',
    'splash potion of long regeneration',
    'splash potion of strong regeneration',
    'splash potion of strength',
    'splash potion of long strength',
    'splash potion of strong strength',
    'splash potion of weakness',
    'splash potion of long weakness',
    'splash potion of luck',
    'splash potion of turtle master',
    'splash potion of long turtle master',
    'splash potion of strong turtle master',
    'splash potion of slow falling',
    'splash potion of long slow falling',
    'lingering potion',
    'lingering potion of water',
    'lingering potion of thick',
    'lingering potion of mundane',
    'lingering potion of awkward',
    'lingering potion of night vision',
    'lingering potion of long night vision',
    'lingering potion of invisibility',
    'lingering potion of long invisibility',
    'lingering potion of leaping',
    'lingering potion of long leaping',
    'lingering potion of strong leaping',
    'lingering potion of fire resistance',
    'lingering potion of long fire resistance',
    'lingering potion of swiftness',
    'lingering potion of extended swiftness',
    'lingering potion of strong swiftness',
    'lingering potion of slowness',
    'lingering potion of long slowness',
    'lingering potion of strong slowness',
    'lingering potion of water breathing',
    'lingering potion of long water breathing',
    'lingering potion of instant health',
    'lingering potion of strong instant health',
    'lingering potion of instant harming',
    'lingering potion of strong instant harming',
    'lingering potion of poisoning',
    'lingering potion of long poisoning',
    'lingering potion of strong poisoning',
    'lingering potion of regeneration',
    'lingering potion of long regeneration',
    'lingering potion of strong regeneration',
    'lingering potion of strength',
    'lingering potion of long strength',
    'lingering potion of strong strength',
    'lingering potion of weakness',
    'lingering potion of long weakness',
    'lingering potion of luck',
    'lingering potion of turtle master',
    'lingering potion of long turtle master',
    'lingering potion of strong turtle master',
    'lingering potion of slow falling',
    'lingering potion of long slow falling',
    'lingering potion of water',
    'lingering potion of thick',
    'lingering potion of mundane',
    'lingering potion of awkward',
    'lingering potion of night vision',
    'lingering potion of long night vision',
    'lingering potion of invisibility',
    'lingering potion of long invisibility',
    'lingering potion of leaping',
    'lingering potion of long leaping',
    'lingering potion of strong leaping',
    'lingering potion of fire resistance',
    'lingering potion of long fire resistance',
    'lingering potion of swiftness',
    'lingering potion of extended swiftness',
    'lingering potion of strong swiftness',
    'lingering potion of slowness',
    'lingering potion of long slowness',
    'lingering potion of strong slowness',
    'lingering potion of water breathing',
    'lingering potion of long water breathing',
    'lingering potion of instant health',
    'lingering potion of strong instant health',
    'lingering potion of instant harming',
    'lingering potion of strong instant harming',
    'lingering potion of poisoning',
    'lingering potion of long poisoning',
    'lingering potion of strong poisoning',
    'lingering potion of regeneration',
    'lingering potion of long regeneration',
    'lingering potion of strong regeneration',
    'lingering potion of strength',
    'lingering potion of long strength',
    'lingering potion of strong strength',
    'lingering potion of weakness',
    'lingering potion of long weakness',
    'lingering potion of luck',
    'lingering potion of turtle master',
    'lingering potion of long turtle master',
    'lingering potion of strong turtle master',
    'lingering potion of slow falling',
    'lingering potion of long slow falling',
    'potion of water',
    'splash potion',
    'lingering potion',
    'spectral arrow',
    'tipped arrow of',
    'water tipped arrow',
    'thick tipped arrow',
    'mundane tipped arrow',
    'awkward tipped arrow',
    'night vision tipped arrow',
    'long night vision tipped arrow',
    'invisibility tipped arrow',
    'long invisibility tipped arrow',
    'leaping tipped arrow',
    'long leaping tipped arrow',
    'strong leaping tipped arrow',
    'fire resistance tipped arrow',
    'long fire resistance tipped arrow',
    'swiftness tipped arrow',
    'extended swiftness tipped arrow',
    'strong swiftness tipped arrow',
    'slowness tipped arrow',
    'long slowness tipped arrow',
    'strong slowness tipped arrow',
    'water breathing tipped arrow',
    'long water breathing tipped arrow',
    'instant health tipped arrow',
    'strong instant health tipped arrow',
    'instant harming tipped arrow',
    'strong instant harming tipped arrow',
    'poisoning tipped arrow',
    'long poisoning tipped arrow',
    'strong poisoning tipped arrow',
    'regeneration tipped arrow',
    'long regeneration tipped arrow',
    'strong regeneration tipped arrow',
    'strength tipped arrow',
    'long strength tipped arrow',
    'strong strength tipped arrow',
    'weakness tipped arrow',
    'long weakness tipped arrow',
    'luck tipped arrow',
    'turtle master tipped arrow',
    'long turtle master tipped arrow',
    'strong turtle master tipped arrow',
    'slow falling tipped arrow',
    'long slow falling tipped arrow',
    'water tipped arrow',
    'thick tipped arrow',
    'mundane tipped arrow',
    'awkward tipped arrow',
    'night vision tipped arrow',
    'long night vision tipped arrow',
    'invisibility tipped arrow',
    'long invisibility tipped arrow',
    'leaping tipped arrow',
    'long leaping tipped arrow',
    'strong leaping tipped arrow',
    'fire resistance tipped arrow',
    'long fire resistance tipped arrow',
    'swiftness tipped arrow',
    'extended swiftness tipped arrow',
    'strong swiftness tipped arrow',
    'slowness tipped arrow',
    'long slowness tipped arrow',
    'strong slowness tipped arrow',
    'water breathing tipped arrow',
    'long water breathing tipped arrow',
    'instant health tipped arrow',
    'strong instant health tipped arrow',
    'instant harming tipped arrow',
    'strong instant harming tipped arrow',
    'poisoning tipped arrow',
    'long poisoning tipped arrow',
    'strong poisoning tipped arrow',
    'regeneration tipped arrow',
    'long regeneration tipped arrow',
    'strong regeneration tipped arrow',
    'strength tipped arrow',
    'long strength tipped arrow',
    'strong strength tipped arrow',
    'weakness tipped arrow',
    'long weakness tipped arrow',
    'luck tipped arrow',
    'turtle master tipped arrow',
    'long turtle master tipped arrow',
    'strong turtle master tipped arrow',
    'slow falling tipped arrow',
    'long slow falling tipped arrow',
    'water tipped arrow',
    'thick tipped arrow',
    'mundane tipped arrow',
    'awkward tipped arrow',
    'night vision tipped arrow',
    'long night vision tipped arrow',
    'invisibility tipped arrow',
    'long invisibility tipped arrow',
    'leaping tipped arrow',
    'long leaping tipped arrow',
    'strong leaping tipped arrow',
    'fire resistance tipped arrow',
    'long fire resistance tipped arrow',
    'swiftness tipped arrow',
    'extended swiftness tipped arrow',
    'strong swiftness tipped arrow',
    'slowness tipped arrow',
    'long slowness tipped arrow',
    'strong slowness tipped arrow',
    'water breathing tipped arrow',
    'long water breathing tipped arrow',
    'instant health tipped arrow',
    'strong instant health tipped arrow',
    'instant harming tipped arrow',
    'strong instant harming tipped arrow',
    'poisoning tipped arrow',
    'long poisoning tipped arrow',
    'strong poisoning tipped arrow',
    'regeneration tipped arrow',
    'long regeneration tipped arrow',
    'strong regeneration tipped arrow',
    'strength tipped arrow',
    'long strength tipped arrow',
    'strong strength tipped arrow',
    'weakness tipped arrow',
    'long weakness tipped arrow',
    'luck tipped arrow',
    'turtle master tipped arrow',
    'long turtle master tipped arrow',
    'strong turtle master tipped arrow',
    'slow falling tipped arrow',
    'long slow falling tipped arrow',
    'arrow',
    'trident',
    'painting',
    'item frame',
    'armor stand',
    'end crystal',
    'glow item frame',
    'brick',
    'bricks',
    'nether brick',
    'nether bricks',
    'resin brick',
    'resin bricks',
    'chicken',
    'rabbit',
    'cod',
    'salmon',
    'pufferfish',
    'tropical fish',
    'snowball',
    'egg',
    'ender pearl',
    "bottle o' enchanting",
    'flight 0 firework rocket',
    'flight 1 firework rocket',
    'flight 2 firework rocket',
    'flight 3 firework rocket',
    'flight 0 firework rocket',
    'flight 1 firework rocket',
    'flight 2 firework rocket',
    'flight 3 firework rocket',
    'flight 1 firework rocket',
    'flight 0 firework rocket',
    'flight 1 firework rocket',
    'flight 2 firework rocket',
    'flight 3 firework rocket',
    'flight 0 firework rocket',
    'flight 1 firework rocket',
    'flight 2 firework rocket',
    'flight 3 firework rocket',
    'flight 0 firework rocket',
    'flight 1 firework rocket',
    'flight 2 firework rocket',
    'flight 3 firework rocket',
    'flight 0 firework rocket',
    'flight 1 firework rocket',
    'flight 2 firework rocket',
    'flight 3 firework rocket',
    'beacon',
    'level 0 beacon',
    'level one beacon',
    'level 2 beacon',
    'level 3 beacon',
    'level 4 beacon',
    'ponder goat horn',
    'sing goat horn',
    'seek goat horn',
    'feel goat horn',
    'admire goat horn',
    'call goat horn',
    'yearn goat horn',
    'dream goat horn',
    'wind charge',
    'tnt block',
    'oak boat',
    'spruce boat',
    'birch boat',
    'jungle boat',
    'acacia boat',
    'dark oak boat',
    'mangrove boat',
    'oak chest boat',
    'spruce chest boat',
    'birch chest boat',
    'jungle chest boat',
    'acacia chest boat',
    'dark oak chest boat',
    'mangrove chest boat',
    'minecart',
    'minecart with tnt',
    'minecart with hopper',
    'cherry boat',
    'cherry chest boat',
    'bamboo raft',
    'bamboo raft with chest',
    'air',
    'allay spawn egg',
    'amethyst shard',
    'angler pottery sherd',
    'apple',
    'archer pottery sherd',
    'armadillo scute',
    'armadillo spawn egg',
    'arms up pottery sherd',
    'axolotl bucket',
    'axolotl spawn egg',
    'baked potato',
    'bat spawn egg',
    'bee spawn egg',
    'beef',
    'beetroot or beetroots',
    'beetroot seeds',
    'beetroot soup',
    'black bundle',
    'black dye',
    'black harness',
    'blade pottery sherd',
    'blaze powder',
    'blaze rod',
    'blaze spawn egg',
    'blue bundle',
    'blue dye',
    'blue egg',
    'blue harness',
    'bogged spawn egg',
    'bolt armor trim smithing template',
    'bone',
    'bone meal',
    'book',
    'bordure indented banner pattern',
    'bow',
    'bowl',
    'bread',
    'breeze rod',
    'breeze spawn egg',
    'brewer pottery sherd',
    'brown bundle',
    'brown dye',
    'brown egg',
    'brown harness',
    'brush',
    'bucket',
    'bundle',
    'burn pottery sherd',
    'camel husk spawn egg',
    'camel spawn egg',
    'carrot or carrots',
    'carrot on a stick',
    'cat spawn egg',
    'cave spider spawn egg',
    'chainmail boots',
    'chainmail chestplate',
    'chainmail helmet',
    'chainmail leggings',
    'charcoal',
    'chest minecart',
    'chicken spawn egg',
    'chorus fruit',
    'clay ball',
    'clock',
    'coal',
    'coast armor trim smithing template',
    'cocoa beans',
    'cod bucket',
    'cod spawn egg',
    'command block minecart',
    'compass',
    'cooked beef',
    'cooked chicken',
    'cooked cod',
    'cooked mutton',
    'cooked porkchop',
    'cooked rabbit',
    'cooked salmon',
    'cookie',
    'copper axe',
    'copper boots',
    'copper chestplate',
    'copper golem spawn egg',
    'copper helmet',
    'copper hoe',
    'copper horse armor',
    'copper ingot',
    'copper leggings',
    'copper nautilus armor',
    'copper nugget',
    'copper pickaxe',
    'copper shovel',
    'copper spear',
    'copper sword',
    'cow spawn egg',
    'creaking spawn egg',
    'creeper banner pattern',
    'creeper spawn egg',
    'crossbow',
    'cyan bundle',
    'cyan dye',
    'cyan harness',
    'danger pottery sherd',
    'debug stick',
    'diamond',
    'diamond axe',
    'diamond boots',
    'diamond chestplate',
    'diamond helmet',
    'diamond hoe',
    'diamond horse armor',
    'diamond leggings',
    'diamond nautilus armor',
    'diamond pickaxe',
    'diamond shovel',
    'diamond spear',
    'diamond sword',
    'disc fragment 5',
    'dolphin spawn egg',
    'donkey spawn egg',
    'dragon breath',
    'dried kelp',
    'drowned spawn egg',
    'dune armor trim smithing template',
    'echo shard',
    'elder guardian spawn egg',
    'elytra',
    'emerald',
    'enchanted book',
    'enchanted golden apple',
    'ender dragon spawn egg',
    'ender eye',
    'enderman spawn egg',
    'endermite spawn egg',
    'evoker spawn egg',
    'explorer pottery sherd',
    'eye armor trim smithing template',
    'feather',
    'fermented spider eye',
    'field masoned banner pattern',
    'filled map',
    'fire charge',
    'firework star',
    'fishing rod',
    'flint',
    'flint and steel',
    'flow armor trim smithing template',
    'flow banner pattern',
    'flow pottery sherd',
    'flower banner pattern',
    'fox spawn egg',
    'friend pottery sherd',
    'frog spawn egg',
    'furnace minecart',
    'ghast spawn egg',
    'ghast tear',
    'glass bottle',
    'glistering melon slice',
    'globe banner pattern',
    'glow berries',
    'glow ink sac',
    'glow squid spawn egg',
    'glowstone dust',
    'goat spawn egg',
    'gold ingot',
    'gold nugget',
    'golden apple',
    'golden axe',
    'golden boots',
    'golden carrot',
    'golden chestplate',
    'golden helmet',
    'golden hoe',
    'golden horse armor',
    'golden leggings',
    'golden nautilus armor',
    'golden pickaxe',
    'golden shovel',
    'golden spear',
    'golden sword',
    'gray bundle',
    'gray dye',
    'gray harness',
    'green bundle',
    'green dye',
    'green harness',
    'guardian spawn egg',
    'gunpowder',
    'guster banner pattern',
    'guster pottery sherd',
    'happy ghast spawn egg',
    'heart of the sea',
    'heart pottery sherd',
    'heartbreak pottery sherd',
    'hoglin spawn egg',
    'honey bottle',
    'honeycomb',
    'horse spawn egg',
    'host armor trim smithing template',
    'howl pottery sherd',
    'husk spawn egg',
    'ink sac',
    'iron axe',
    'iron boots',
    'iron chestplate',
    'iron golem spawn egg',
    'iron helmet',
    'iron hoe',
    'iron horse armor',
    'iron ingot',
    'iron leggings',
    'iron nautilus armor',
    'iron nugget',
    'iron pickaxe',
    'iron shovel',
    'iron spear',
    'iron sword',
    'knowledge book',
    'lapis lazuli',
    'lava bucket',
    'lead',
    'leather',
    'leather boots',
    'leather chestplate',
    'leather helmet',
    'leather horse armor',
    'leather leggings',
    'light blue bundle',
    'light blue dye',
    'light blue harness',
    'light gray bundle',
    'light gray dye',
    'light gray harness',
    'lime bundle',
    'lime dye',
    'lime harness',
    'llama spawn egg',
    'mace',
    'magenta bundle',
    'magenta dye',
    'magenta harness',
    'magma cream',
    'magma cube spawn egg',
    'map',
    'melon seeds',
    'melon slice',
    'milk bucket',
    'miner pottery sherd',
    'mojang banner pattern',
    'mooshroom spawn egg',
    'mourner pottery sherd',
    'mule spawn egg',
    'mushroom stew',
    'music disc 5',
    'music disc 11',
    'music disc 13',
    'music disc blocks',
    'music disc cat',
    'music disc chirp',
    'music disc creator',
    'music disc creator music box',
    'music disc far',
    'music disc lava chicken',
    'music disc mall',
    'music disc mellohi',
    'music disc otherside',
    'music disc pigstep',
    'music disc precipice',
    'music disc relic',
    'music disc stal',
    'music disc strad',
    'music disc tears',
    'music disc wait',
    'music disc ward',
    'mutton',
    'name tag',
    'nautilus shell',
    'nautilus spawn egg',
    'nether star',
    'netherite axe',
    'netherite boots',
    'netherite chestplate',
    'netherite helmet',
    'netherite hoe',
    'netherite horse armor',
    'netherite ingot',
    'netherite leggings',
    'netherite nautilus armor',
    'netherite pickaxe',
    'netherite scrap',
    'netherite shovel',
    'netherite spear',
    'netherite sword',
    'netherite upgrade smithing template',
    'ocelot spawn egg',
    'ominous bottle',
    'ominous trial key',
    'orange bundle',
    'orange dye',
    'orange harness',
    'pale oak boat',
    'pale oak chest boat',
    'panda spawn egg',
    'paper',
    'parched spawn egg',
    'parrot spawn egg',
    'phantom membrane',
    'phantom spawn egg',
    'pig spawn egg',
    'piglin banner pattern',
    'piglin brute spawn egg',
    'piglin spawn egg',
    'pillager spawn egg',
    'pink bundle',
    'pink dye',
    'pink harness',
    'pitcher pod',
    'plenty pottery sherd',
    'poisonous potato',
    'polar bear spawn egg',
    'popped chorus fruit',
    'porkchop',
    'potato',
    'powder snow bucket',
    'prismarine crystals',
    'prismarine shard',
    'prize pottery sherd',
    'pufferfish bucket',
    'pufferfish spawn egg',
    'pumpkin pie',
    'pumpkin seeds',
    'purple bundle',
    'purple dye',
    'purple harness',
    'quartz',
    'rabbit foot',
    'rabbit hide',
    'rabbit spawn egg',
    'rabbit stew',
    'raiser armor trim smithing template',
    'ravager spawn egg',
    'raw copper',
    'raw gold',
    'raw iron',
    'recovery compass',
    'red bundle',
    'red dye',
    'red harness',
    'redstone',
    'rib armor trim smithing template',
    'rotten flesh',
    'saddle',
    'salmon bucket',
    'salmon spawn egg',
    'scrape pottery sherd',
    'sentry armor trim smithing template',
    'shaper armor trim smithing template',
    'sheaf pottery sherd',
    'shears',
    'sheep spawn egg',
    'shelter pottery sherd',
    'shield',
    'shulker shell',
    'shulker spawn egg',
    'silence armor trim smithing template',
    'silverfish spawn egg',
    'skeleton horse spawn egg',
    'skeleton spawn egg',
    'skull banner pattern',
    'skull pottery sherd',
    'slime ball',
    'slime spawn egg',
    'sniffer spawn egg',
    'snort pottery sherd',
    'snout armor trim smithing template',
    'snow golem spawn egg',
    'spider eye',
    'spider spawn egg',
    'spire armor trim smithing template',
    'spyglass',
    'squid spawn egg',
    'stick',
    'stone axe',
    'stone hoe',
    'stone pickaxe',
    'stone shovel',
    'stone spear',
    'stone sword',
    'stray spawn egg',
    'strider spawn egg',
    'string',
    'sugar',
    'suspicious stew',
    'sweet berries',
    'tadpole bucket',
    'tadpole spawn egg',
    'tide armor trim smithing template',
    'torchflower seeds',
    'totem of undying',
    'trader llama spawn egg',
    'trial key',
    'tropical fish bucket',
    'tropical fish spawn egg',
    'turtle helmet',
    'turtle scute',
    'turtle spawn egg',
    'vex armor trim smithing template',
    'vex spawn egg',
    'villager spawn egg',
    'vindicator spawn egg',
    'wandering trader spawn egg',
    'ward armor trim smithing template',
    'warden spawn egg',
    'warped fungus on a stick',
    'water bucket',
    'wayfinder armor trim smithing template',
    'wheat seeds',
    'white bundle',
    'white dye',
    'white harness',
    'wild armor trim smithing template',
    'witch spawn egg',
    'wither skeleton spawn egg',
    'wither spawn egg',
    'wolf armor',
    'wolf spawn egg',
    'wooden axe',
    'wooden hoe',
    'wooden pickaxe',
    'wooden shovel',
    'wooden spear',
    'wooden sword',
    'writable book',
    'written book',
    'yellow bundle',
    'yellow dye',
    'yellow harness',
    'zoglin spawn egg',
    'zombie horse spawn egg',
    'zombie nautilus spawn egg',
    'zombie spawn egg',
    'zombie villager spawn egg',
    'zombified piglin spawn egg',
    'acacia button',
    'acacia door',
    'acacia fence',
    'acacia fence gate',
    'acacia hanging sign',
    'acacia leaves',
    'acacia log',
    'acacia planks',
    'acacia pressure plate',
    'acacia sapling',
    'acacia shelf',
    'acacia sign',
    'acacia slab',
    'acacia stairs',
    'acacia trapdoor',
    'acacia wood',
    'activator rail',
    'allium',
    'amethyst block',
    'amethyst cluster',
    'ancient debris',
    'andesite',
    'andesite slab',
    'andesite stairs',
    'andesite wall',
    'anvil',
    'azalea',
    'azalea leaves',
    'azure bluet',
    'bamboo',
    'bamboo block',
    'bamboo button',
    'bamboo door',
    'bamboo fence',
    'bamboo fence gate',
    'bamboo hanging sign',
    'bamboo mosaic',
    'bamboo mosaic slab',
    'bamboo mosaic stairs',
    'bamboo planks',
    'bamboo pressure plate',
    'bamboo shelf',
    'bamboo sign',
    'bamboo slab',
    'bamboo stairs',
    'bamboo trapdoor',
    'barrel',
    'barrier',
    'basalt',
    'bedrock',
    'bee nest',
    'beehive',
    'bell',
    'big dripleaf',
    'birch button',
    'birch door',
    'birch fence',
    'birch fence gate',
    'birch hanging sign',
    'birch leaves',
    'birch log',
    'birch planks',
    'birch pressure plate',
    'birch sapling',
    'birch shelf',
    'birch sign',
    'birch slab',
    'birch stairs',
    'birch trapdoor',
    'birch wood',
    'black banner',
    'black bed',
    'black candle',
    'black carpet',
    'black concrete',
    'black concrete powder',
    'black glazed terracotta',
    'black shulker box',
    'black stained glass',
    'black stained glass pane',
    'black terracotta',
    'black wool',
    'blackstone',
    'blackstone slab',
    'blackstone stairs',
    'blackstone wall',
    'blast furnace',
    'blue banner',
    'blue bed',
    'blue candle',
    'blue carpet',
    'blue concrete',
    'blue concrete powder',
    'blue glazed terracotta',
    'blue ice',
    'blue orchid',
    'blue shulker box',
    'blue stained glass',
    'blue stained glass pane',
    'blue terracotta',
    'blue wool',
    'bone block',
    'bookshelf',
    'brain coral',
    'brain coral block',
    'brain coral fan',
    'brewing stand',
    'brick slab',
    'brick stairs',
    'brick wall',
    'brown banner',
    'brown bed',
    'brown candle',
    'brown carpet',
    'brown concrete',
    'brown concrete powder',
    'brown glazed terracotta',
    'brown mushroom',
    'brown mushroom block',
    'brown shulker box',
    'brown stained glass',
    'brown stained glass pane',
    'brown terracotta',
    'brown wool',
    'bubble coral',
    'bubble coral block',
    'bubble coral fan',
    'budding amethyst',
    'bush',
    'cactus',
    'cactus flower',
    'cake',
    'calcite',
    'calibrated sculk sensor',
    'campfire',
    'candle',
    'cartography table',
    'carved pumpkin',
    'cauldron',
    'chain command block',
    'cherry button',
    'cherry door',
    'cherry fence',
    'cherry fence gate',
    'cherry hanging sign',
    'cherry leaves',
    'cherry log',
    'cherry planks',
    'cherry pressure plate',
    'cherry sapling',
    'cherry shelf',
    'cherry sign',
    'cherry slab',
    'cherry stairs',
    'cherry trapdoor',
    'cherry wood',
    'chest',
    'chipped anvil',
    'chiseled bookshelf',
    'chiseled copper',
    'chiseled deepslate',
    'chiseled nether bricks',
    'chiseled polished blackstone',
    'chiseled quartz block',
    'chiseled red sandstone',
    'chiseled resin bricks',
    'chiseled sandstone',
    'chiseled stone bricks',
    'chiseled tuff',
    'chiseled tuff bricks',
    'chorus flower',
    'chorus plant',
    'clay',
    'closed eyeblossom',
    'coal block',
    'coal ore',
    'coarse dirt',
    'cobbled deepslate',
    'cobbled deepslate slab',
    'cobbled deepslate stairs',
    'cobbled deepslate wall',
    'cobblestone',
    'cobblestone slab',
    'cobblestone stairs',
    'cobblestone wall',
    'cobweb',
    'command block',
    'comparator',
    'composter',
    'conduit',
    'copper bars',
    'copper block',
    'copper bulb',
    'copper chain',
    'copper chest',
    'copper door',
    'copper golem statue',
    'copper grate',
    'copper lantern',
    'copper ore',
    'copper torch',
    'copper trapdoor',
    'cornflower',
    'cracked deepslate bricks',
    'cracked deepslate tiles',
    'cracked nether bricks',
    'cracked polished blackstone bricks',
    'cracked stone bricks',
    'crafter',
    'crafting table',
    'creaking heart',
    'creeper head',
    'crimson button',
    'crimson door',
    'crimson fence',
    'crimson fence gate',
    'crimson fungus',
    'crimson hanging sign',
    'crimson hyphae',
    'crimson nylium',
    'crimson planks',
    'crimson pressure plate',
    'crimson roots',
    'crimson shelf',
    'crimson sign',
    'crimson slab',
    'crimson stairs',
    'crimson stem',
    'crimson trapdoor',
    'crying obsidian',
    'cut copper',
    'cut copper slab',
    'cut copper stairs',
    'cut red sandstone',
    'cut red sandstone slab',
    'cut sandstone',
    'cut sandstone slab',
    'cyan banner',
    'cyan bed',
    'cyan candle',
    'cyan carpet',
    'cyan concrete',
    'cyan concrete powder',
    'cyan glazed terracotta',
    'cyan shulker box',
    'cyan stained glass',
    'cyan stained glass pane',
    'cyan terracotta',
    'cyan wool',
    'damaged anvil',
    'dandelion',
    'dark oak button',
    'dark oak door',
    'dark oak fence',
    'dark oak fence gate',
    'dark oak hanging sign',
    'dark oak leaves',
    'dark oak log',
    'dark oak planks',
    'dark oak pressure plate',
    'dark oak sapling',
    'dark oak shelf',
    'dark oak sign',
    'dark oak slab',
    'dark oak stairs',
    'dark oak trapdoor',
    'dark oak wood',
    'dark prismarine',
    'dark prismarine slab',
    'dark prismarine stairs',
    'daylight detector',
    'dead brain coral',
    'dead brain coral block',
    'dead brain coral fan',
    'dead bubble coral',
    'dead bubble coral block',
    'dead bubble coral fan',
    'dead bush',
    'dead fire coral',
    'dead fire coral block',
    'dead fire coral fan',
    'dead horn coral',
    'dead horn coral block',
    'dead horn coral fan',
    'dead tube coral',
    'dead tube coral block',
    'dead tube coral fan',
    'decorated pot',
    'deepslate',
    'deepslate brick slab',
    'deepslate brick stairs',
    'deepslate brick wall',
    'deepslate bricks',
    'deepslate coal ore',
    'deepslate copper ore',
    'deepslate diamond ore',
    'deepslate emerald ore',
    'deepslate gold ore',
    'deepslate iron ore',
    'deepslate lapis ore',
    'deepslate redstone ore',
    'deepslate tile slab',
    'deepslate tile stairs',
    'deepslate tile wall',
    'deepslate tiles',
    'detector rail',
    'diamond block',
    'diamond ore',
    'diorite',
    'diorite slab',
    'diorite stairs',
    'diorite wall',
    'dirt',
    'dirt path',
    'dispenser',
    'dragon egg',
    'dragon head',
    'dried ghast',
    'dried kelp block',
    'dripstone block',
    'dropper',
    'emerald block',
    'emerald ore',
    'enchanting table',
    'end portal frame',
    'end rod',
    'end stone',
    'end stone brick slab',
    'end stone brick stairs',
    'end stone brick wall',
    'end stone bricks',
    'ender chest',
    'exposed chiseled copper',
    'exposed copper',
    'exposed copper bars',
    'exposed copper bulb',
    'exposed copper chain',
    'exposed copper chest',
    'exposed copper door',
    'exposed copper golem statue',
    'exposed copper grate',
    'exposed copper lantern',
    'exposed copper trapdoor',
    'exposed cut copper',
    'exposed cut copper slab',
    'exposed cut copper stairs',
    'exposed lightning rod',
    'farmland',
    'fern',
    'fire coral',
    'fire coral block',
    'fire coral fan',
    'firefly bush',
    'fletching table',
    'flower pot',
    'flowering azalea',
    'flowering azalea leaves',
    'frogspawn',
    'furnace',
    'gilded blackstone',
    'glass',
    'glass pane',
    'glow lichen',
    'glowstone',
    'gold block',
    'gold ore',
    'golden dandelion',
    'granite',
    'granite slab',
    'granite stairs',
    'granite wall',
    'grass block',
    'gravel',
    'gray banner',
    'gray bed',
    'gray candle',
    'gray carpet',
    'gray concrete',
    'gray concrete powder',
    'gray glazed terracotta',
    'gray shulker box',
    'gray stained glass',
    'gray stained glass pane',
    'gray terracotta',
    'gray wool',
    'green banner',
    'green bed',
    'green candle',
    'green carpet',
    'green concrete',
    'green concrete powder',
    'green glazed terracotta',
    'green shulker box',
    'green stained glass',
    'green stained glass pane',
    'green terracotta',
    'green wool',
    'grindstone',
    'hanging roots',
    'hay block',
    'heavy core',
    'heavy weighted pressure plate',
    'honey block',
    'honeycomb block',
    'hopper',
    'horn coral',
    'horn coral block',
    'horn coral fan',
    'ice',
    'infested chiseled stone bricks',
    'infested cobblestone',
    'infested cracked stone bricks',
    'infested deepslate',
    'infested mossy stone bricks',
    'infested stone',
    'infested stone bricks',
    'iron bars',
    'iron block',
    'iron chain',
    'iron door',
    'iron ore',
    'iron trapdoor',
    'jack o lantern',
    'jigsaw',
    'jukebox',
    'jungle button',
    'jungle door',
    'jungle fence',
    'jungle fence gate',
    'jungle hanging sign',
    'jungle leaves',
    'jungle log',
    'jungle planks',
    'jungle pressure plate',
    'jungle sapling',
    'jungle shelf',
    'jungle sign',
    'jungle slab',
    'jungle stairs',
    'jungle trapdoor',
    'jungle wood',
    'kelp',
    'ladder',
    'lantern',
    'lapis block',
    'lapis ore',
    'large amethyst bud',
    'large fern',
    'leaf litter',
    'lectern',
    'lever',
    'light',
    'light blue banner',
    'light blue bed',
    'light blue candle',
    'light blue carpet',
    'light blue concrete',
    'light blue concrete powder',
    'light blue glazed terracotta',
    'light blue shulker box',
    'light blue stained glass',
    'light blue stained glass pane',
    'light blue terracotta',
    'light blue wool',
    'light gray banner',
    'light gray bed',
    'light gray candle',
    'light gray carpet',
    'light gray concrete',
    'light gray concrete powder',
    'light gray glazed terracotta',
    'light gray shulker box',
    'light gray stained glass',
    'light gray stained glass pane',
    'light gray terracotta',
    'light gray wool',
    'light weighted pressure plate',
    'lightning rod',
    'lilac',
    'lily of the valley',
    'lily pad',
    'lime banner',
    'lime bed',
    'lime candle',
    'lime carpet',
    'lime concrete',
    'lime concrete powder',
    'lime glazed terracotta',
    'lime shulker box',
    'lime stained glass',
    'lime stained glass pane',
    'lime terracotta',
    'lime wool',
    'lodestone',
    'loom',
    'magenta banner',
    'magenta bed',
    'magenta candle',
    'magenta carpet',
    'magenta concrete',
    'magenta concrete powder',
    'magenta glazed terracotta',
    'magenta shulker box',
    'magenta stained glass',
    'magenta stained glass pane',
    'magenta terracotta',
    'magenta wool',
    'magma block',
    'mangrove button',
    'mangrove door',
    'mangrove fence',
    'mangrove fence gate',
    'mangrove hanging sign',
    'mangrove leaves',
    'mangrove log',
    'mangrove planks',
    'mangrove pressure plate',
    'mangrove propagule',
    'mangrove roots',
    'mangrove shelf',
    'mangrove sign',
    'mangrove slab',
    'mangrove stairs',
    'mangrove trapdoor',
    'mangrove wood',
    'medium amethyst bud',
    'melon',
    'moss block',
    'moss carpet',
    'mossy cobblestone',
    'mossy cobblestone slab',
    'mossy cobblestone stairs',
    'mossy cobblestone wall',
    'mossy stone brick slab',
    'mossy stone brick stairs',
    'mossy stone brick wall',
    'mossy stone bricks',
    'mud',
    'mud brick slab',
    'mud brick stairs',
    'mud brick wall',
    'mud bricks',
    'muddy mangrove roots',
    'mushroom stem',
    'mycelium',
    'nether brick fence',
    'nether brick slab',
    'nether brick stairs',
    'nether brick wall',
    'nether gold ore',
    'nether quartz ore',
    'nether sprouts',
    'nether wart',
    'nether wart block',
    'netherite block',
    'netherrack',
    'note block',
    'oak button',
    'oak door',
    'oak fence',
    'oak fence gate',
    'oak hanging sign',
    'oak leaves',
    'oak log',
    'oak planks',
    'oak pressure plate',
    'oak sapling',
    'oak shelf',
    'oak sign',
    'oak slab',
    'oak stairs',
    'oak trapdoor',
    'oak wood',
    'observer',
    'obsidian',
    'ochre froglight',
    'open eyeblossom',
    'orange banner',
    'orange bed',
    'orange candle',
    'orange carpet',
    'orange concrete',
    'orange concrete powder',
    'orange glazed terracotta',
    'orange shulker box',
    'orange stained glass',
    'orange stained glass pane',
    'orange terracotta',
    'orange tulip',
    'orange wool',
    'oxeye daisy',
    'oxidized chiseled copper',
    'oxidized copper',
    'oxidized copper bars',
    'oxidized copper bulb',
    'oxidized copper chain',
    'oxidized copper chest',
    'oxidized copper door',
    'oxidized copper golem statue',
    'oxidized copper grate',
    'oxidized copper lantern',
    'oxidized copper trapdoor',
    'oxidized cut copper',
    'oxidized cut copper slab',
    'oxidized cut copper stairs',
    'oxidized lightning rod',
    'packed ice',
    'packed mud',
    'pale hanging moss',
    'pale moss block',
    'pale moss carpet',
    'pale oak button',
    'pale oak door',
    'pale oak fence',
    'pale oak fence gate',
    'pale oak hanging sign',
    'pale oak leaves',
    'pale oak log',
    'pale oak planks',
    'pale oak pressure plate',
    'pale oak sapling',
    'pale oak shelf',
    'pale oak sign',
    'pale oak slab',
    'pale oak stairs',
    'pale oak trapdoor',
    'pale oak wood',
    'pearlescent froglight',
    'peony',
    'petrified oak slab',
    'piglin head',
    'pink banner',
    'pink bed',
    'pink candle',
    'pink carpet',
    'pink concrete',
    'pink concrete powder',
    'pink glazed terracotta',
    'pink petals',
    'pink shulker box',
    'pink stained glass',
    'pink stained glass pane',
    'pink terracotta',
    'pink tulip',
    'pink wool',
    'piston',
    'pitcher plant',
    'player head',
    'podzol',
    'pointed dripstone',
    'polished andesite',
    'polished andesite slab',
    'polished andesite stairs',
    'polished basalt',
    'polished blackstone',
    'polished blackstone brick slab',
    'polished blackstone brick stairs',
    'polished blackstone brick wall',
    'polished blackstone bricks',
    'polished blackstone button',
    'polished blackstone pressure plate',
    'polished blackstone slab',
    'polished blackstone stairs',
    'polished blackstone wall',
    'polished deepslate',
    'polished deepslate slab',
    'polished deepslate stairs',
    'polished deepslate wall',
    'polished diorite',
    'polished diorite slab',
    'polished diorite stairs',
    'polished granite',
    'polished granite slab',
    'polished granite stairs',
    'polished tuff',
    'polished tuff slab',
    'polished tuff stairs',
    'polished tuff wall',
    'poppy',
    'powered rail',
    'prismarine',
    'prismarine brick slab',
    'prismarine brick stairs',
    'prismarine bricks',
    'prismarine slab',
    'prismarine stairs',
    'prismarine wall',
    'pumpkin',
    'purple banner',
    'purple bed',
    'purple candle',
    'purple carpet',
    'purple concrete',
    'purple concrete powder',
    'purple glazed terracotta',
    'purple shulker box',
    'purple stained glass',
    'purple stained glass pane',
    'purple terracotta',
    'purple wool',
    'purpur block',
    'purpur pillar',
    'purpur slab',
    'purpur stairs',
    'quartz block',
    'quartz bricks',
    'quartz pillar',
    'quartz slab',
    'quartz stairs',
    'rail',
    'raw copper block',
    'raw gold block',
    'raw iron block',
    'red banner',
    'red bed',
    'red candle',
    'red carpet',
    'red concrete',
    'red concrete powder',
    'red glazed terracotta',
    'red mushroom',
    'red mushroom block',
    'red nether brick slab',
    'red nether brick stairs',
    'red nether brick wall',
    'red nether bricks',
    'red sand',
    'red sandstone',
    'red sandstone slab',
    'red sandstone stairs',
    'red sandstone wall',
    'red shulker box',
    'red stained glass',
    'red stained glass pane',
    'red terracotta',
    'red tulip',
    'red wool',
    'redstone block',
    'redstone lamp',
    'redstone ore',
    'redstone torch',
    'reinforced deepslate',
    'repeater',
    'repeating command block',
    'resin block',
    'resin brick slab',
    'resin brick stairs',
    'resin brick wall',
    'resin clump',
    'respawn anchor',
    'rooted dirt',
    'rose bush',
    'sand',
    'sandstone',
    'sandstone slab',
    'sandstone stairs',
    'sandstone wall',
    'scaffolding',
    'sculk',
    'sculk catalyst',
    'sculk sensor',
    'sculk shrieker',
    'sculk vein',
    'sea lantern',
    'sea pickle',
    'seagrass',
    'short dry grass',
    'short grass',
    'shroomlight',
    'shulker box',
    'skeleton skull',
    'slime block',
    'small amethyst bud',
    'small dripleaf',
    'smithing table',
    'smoker',
    'smooth basalt',
    'smooth quartz',
    'smooth quartz slab',
    'smooth quartz stairs',
    'smooth red sandstone',
    'smooth red sandstone slab',
    'smooth red sandstone stairs',
    'smooth sandstone',
    'smooth sandstone slab',
    'smooth sandstone stairs',
    'smooth stone',
    'smooth stone slab',
    'sniffer egg',
    'snow',
    'snow block',
    'soul campfire',
    'soul lantern',
    'soul sand',
    'soul soil',
    'soul torch',
    'spawner',
    'sponge',
    'spore blossom',
    'spruce button',
    'spruce door',
    'spruce fence',
    'spruce fence gate',
    'spruce hanging sign',
    'spruce leaves',
    'spruce log',
    'spruce planks',
    'spruce pressure plate',
    'spruce sapling',
    'spruce shelf',
    'spruce sign',
    'spruce slab',
    'spruce stairs',
    'spruce trapdoor',
    'spruce wood',
    'sticky piston',
    'stone',
    'stone brick slab',
    'stone brick stairs',
    'stone brick wall',
    'stone bricks',
    'stone button',
    'stone pressure plate',
    'stone slab',
    'stone stairs',
    'stonecutter',
    'stripped acacia log',
    'stripped acacia wood',
    'stripped bamboo block',
    'stripped birch log',
    'stripped birch wood',
    'stripped cherry log',
    'stripped cherry wood',
    'stripped crimson hyphae',
    'stripped crimson stem',
    'stripped dark oak log',
    'stripped dark oak wood',
    'stripped jungle log',
    'stripped jungle wood',
    'stripped mangrove log',
    'stripped mangrove wood',
    'stripped oak log',
    'stripped oak wood',
    'stripped pale oak log',
    'stripped pale oak wood',
    'stripped spruce log',
    'stripped spruce wood',
    'stripped warped hyphae',
    'stripped warped stem',
    'structure block',
    'structure void',
    'sugar cane',
    'sunflower',
    'suspicious gravel',
    'suspicious sand',
    'tall dry grass',
    'tall grass',
    'target',
    'terracotta',
    'test block',
    'test instance block',
    'tinted glass',
    'torch',
    'torchflower',
    'trapped chest',
    'trial spawner',
    'tripwire hook',
    'tube coral',
    'tube coral block',
    'tube coral fan',
    'tuff',
    'tuff brick slab',
    'tuff brick stairs',
    'tuff brick wall',
    'tuff bricks',
    'tuff slab',
    'tuff stairs',
    'tuff wall',
    'turtle egg',
    'twisting vines',
    'vault',
    'verdant froglight',
    'vine',
    'warped button',
    'warped door',
    'warped fence',
    'warped fence gate',
    'warped fungus',
    'warped hanging sign',
    'warped hyphae',
    'warped nylium',
    'warped planks',
    'warped pressure plate',
    'warped roots',
    'warped shelf',
    'warped sign',
    'warped slab',
    'warped stairs',
    'warped stem',
    'warped trapdoor',
    'warped wart block',
    'waxed chiseled copper',
    'waxed copper bars',
    'waxed copper block',
    'waxed copper bulb',
    'waxed copper chain',
    'waxed copper chest',
    'waxed copper door',
    'waxed copper golem statue',
    'waxed copper grate',
    'waxed copper lantern',
    'waxed copper trapdoor',
    'waxed cut copper',
    'waxed cut copper slab',
    'waxed cut copper stairs',
    'waxed exposed chiseled copper',
    'waxed exposed copper',
    'waxed exposed copper bars',
    'waxed exposed copper bulb',
    'waxed exposed copper chain',
    'waxed exposed copper chest',
    'waxed exposed copper door',
    'waxed exposed copper golem statue',
    'waxed exposed copper grate',
    'waxed exposed copper lantern',
    'waxed exposed copper trapdoor',
    'waxed exposed cut copper',
    'waxed exposed cut copper slab',
    'waxed exposed cut copper stairs',
    'waxed exposed lightning rod',
    'waxed lightning rod',
    'waxed oxidized chiseled copper',
    'waxed oxidized copper',
    'waxed oxidized copper bars',
    'waxed oxidized copper bulb',
    'waxed oxidized copper chain',
    'waxed oxidized copper chest',
    'waxed oxidized copper door',
    'waxed oxidized copper golem statue',
    'waxed oxidized copper grate',
    'waxed oxidized copper lantern',
    'waxed oxidized copper trapdoor',
    'waxed oxidized cut copper',
    'waxed oxidized cut copper slab',
    'waxed oxidized cut copper stairs',
    'waxed oxidized lightning rod',
    'waxed weathered chiseled copper',
    'waxed weathered copper',
    'waxed weathered copper bars',
    'waxed weathered copper bulb',
    'waxed weathered copper chain',
    'waxed weathered copper chest',
    'waxed weathered copper door',
    'waxed weathered copper golem statue',
    'waxed weathered copper grate',
    'waxed weathered copper lantern',
    'waxed weathered copper trapdoor',
    'waxed weathered cut copper',
    'waxed weathered cut copper slab',
    'waxed weathered cut copper stairs',
    'waxed weathered lightning rod',
    'weathered chiseled copper',
    'weathered copper',
    'weathered copper bars',
    'weathered copper bulb',
    'weathered copper chain',
    'weathered copper chest',
    'weathered copper door',
    'weathered copper golem statue',
    'weathered copper grate',
    'weathered copper lantern',
    'weathered copper trapdoor',
    'weathered cut copper',
    'weathered cut copper slab',
    'weathered cut copper stairs',
    'weathered lightning rod',
    'weeping vines',
    'wet sponge',
    'wheat',
    'white banner',
    'white bed',
    'white candle',
    'white carpet',
    'white concrete',
    'white concrete powder',
    'white glazed terracotta',
    'white shulker box',
    'white stained glass',
    'white stained glass pane',
    'white terracotta',
    'white tulip',
    'white wool',
    'wildflowers',
    'wither rose',
    'wither skeleton skull',
    'yellow banner',
    'yellow bed',
    'yellow candle',
    'yellow carpet',
    'yellow concrete',
    'yellow concrete powder',
    'yellow glazed terracotta',
    'yellow shulker box',
    'yellow stained glass',
    'yellow stained glass pane',
    'yellow terracotta',
    'yellow wool',
    'zombie head',
  ],
}

export const BlockDatas: SkriptType = {
  name: 'block',
  options: [
    'bricks',
    'nether bricks',
    'resin bricks',
    'beacon',
    'level 0 beacon',
    'level one beacon',
    'level 2 beacon',
    'level 3 beacon',
    'level 4 beacon',
    'tnt block',
    'air',
    'beetroot or beetroots',
    'carrot or carrots',
    'acacia button',
    'acacia door',
    'acacia fence',
    'acacia fence gate',
    'acacia hanging sign',
    'acacia leaves',
    'acacia log',
    'acacia planks',
    'acacia pressure plate',
    'acacia sapling',
    'acacia shelf',
    'acacia sign',
    'acacia slab',
    'acacia stairs',
    'acacia trapdoor',
    'acacia wall hanging sign',
    'acacia wall sign',
    'acacia wood',
    'activator rail',
    'allium',
    'amethyst block',
    'amethyst cluster',
    'ancient debris',
    'andesite',
    'andesite slab',
    'andesite stairs',
    'andesite wall',
    'anvil',
    'attached melon stem',
    'attached pumpkin stem',
    'azalea',
    'azalea leaves',
    'azure bluet',
    'bamboo',
    'bamboo block',
    'bamboo button',
    'bamboo door',
    'bamboo fence',
    'bamboo fence gate',
    'bamboo hanging sign',
    'bamboo mosaic',
    'bamboo mosaic slab',
    'bamboo mosaic stairs',
    'bamboo planks',
    'bamboo pressure plate',
    'bamboo sapling',
    'bamboo shelf',
    'bamboo sign',
    'bamboo slab',
    'bamboo stairs',
    'bamboo trapdoor',
    'bamboo wall hanging sign',
    'bamboo wall sign',
    'barrel',
    'barrier',
    'basalt',
    'bedrock',
    'bee nest',
    'beehive',
    'bell',
    'big dripleaf',
    'big dripleaf stem',
    'birch button',
    'birch door',
    'birch fence',
    'birch fence gate',
    'birch hanging sign',
    'birch leaves',
    'birch log',
    'birch planks',
    'birch pressure plate',
    'birch sapling',
    'birch shelf',
    'birch sign',
    'birch slab',
    'birch stairs',
    'birch trapdoor',
    'birch wall hanging sign',
    'birch wall sign',
    'birch wood',
    'black banner',
    'black bed',
    'black candle',
    'black candle cake',
    'black carpet',
    'black concrete',
    'black concrete powder',
    'black glazed terracotta',
    'black shulker box',
    'black stained glass',
    'black stained glass pane',
    'black terracotta',
    'black wall banner',
    'black wool',
    'blackstone',
    'blackstone slab',
    'blackstone stairs',
    'blackstone wall',
    'blast furnace',
    'blue banner',
    'blue bed',
    'blue candle',
    'blue candle cake',
    'blue carpet',
    'blue concrete',
    'blue concrete powder',
    'blue glazed terracotta',
    'blue ice',
    'blue orchid',
    'blue shulker box',
    'blue stained glass',
    'blue stained glass pane',
    'blue terracotta',
    'blue wall banner',
    'blue wool',
    'bone block',
    'bookshelf',
    'brain coral',
    'brain coral block',
    'brain coral fan',
    'brain coral wall fan',
    'brewing stand',
    'brick slab',
    'brick stairs',
    'brick wall',
    'brown banner',
    'brown bed',
    'brown candle',
    'brown candle cake',
    'brown carpet',
    'brown concrete',
    'brown concrete powder',
    'brown glazed terracotta',
    'brown mushroom',
    'brown mushroom block',
    'brown shulker box',
    'brown stained glass',
    'brown stained glass pane',
    'brown terracotta',
    'brown wall banner',
    'brown wool',
    'bubble column',
    'bubble coral',
    'bubble coral block',
    'bubble coral fan',
    'bubble coral wall fan',
    'budding amethyst',
    'bush',
    'cactus',
    'cactus flower',
    'cake',
    'calcite',
    'calibrated sculk sensor',
    'campfire',
    'candle',
    'candle cake',
    'cartography table',
    'carved pumpkin',
    'cauldron',
    'cave air',
    'cave vines',
    'cave vines plant',
    'chain command block',
    'cherry button',
    'cherry door',
    'cherry fence',
    'cherry fence gate',
    'cherry hanging sign',
    'cherry leaves',
    'cherry log',
    'cherry planks',
    'cherry pressure plate',
    'cherry sapling',
    'cherry shelf',
    'cherry sign',
    'cherry slab',
    'cherry stairs',
    'cherry trapdoor',
    'cherry wall hanging sign',
    'cherry wall sign',
    'cherry wood',
    'chest',
    'chipped anvil',
    'chiseled bookshelf',
    'chiseled copper',
    'chiseled deepslate',
    'chiseled nether bricks',
    'chiseled polished blackstone',
    'chiseled quartz block',
    'chiseled red sandstone',
    'chiseled resin bricks',
    'chiseled sandstone',
    'chiseled stone bricks',
    'chiseled tuff',
    'chiseled tuff bricks',
    'chorus flower',
    'chorus plant',
    'clay',
    'closed eyeblossom',
    'coal block',
    'coal ore',
    'coarse dirt',
    'cobbled deepslate',
    'cobbled deepslate slab',
    'cobbled deepslate stairs',
    'cobbled deepslate wall',
    'cobblestone',
    'cobblestone slab',
    'cobblestone stairs',
    'cobblestone wall',
    'cobweb',
    'cocoa',
    'command block',
    'comparator',
    'composter',
    'conduit',
    'copper bars',
    'copper block',
    'copper bulb',
    'copper chain',
    'copper chest',
    'copper door',
    'copper golem statue',
    'copper grate',
    'copper lantern',
    'copper ore',
    'copper torch',
    'copper trapdoor',
    'copper wall torch',
    'cornflower',
    'cracked deepslate bricks',
    'cracked deepslate tiles',
    'cracked nether bricks',
    'cracked polished blackstone bricks',
    'cracked stone bricks',
    'crafter',
    'crafting table',
    'creaking heart',
    'creeper head',
    'creeper wall head',
    'crimson button',
    'crimson door',
    'crimson fence',
    'crimson fence gate',
    'crimson fungus',
    'crimson hanging sign',
    'crimson hyphae',
    'crimson nylium',
    'crimson planks',
    'crimson pressure plate',
    'crimson roots',
    'crimson shelf',
    'crimson sign',
    'crimson slab',
    'crimson stairs',
    'crimson stem',
    'crimson trapdoor',
    'crimson wall hanging sign',
    'crimson wall sign',
    'crying obsidian',
    'cut copper',
    'cut copper slab',
    'cut copper stairs',
    'cut red sandstone',
    'cut red sandstone slab',
    'cut sandstone',
    'cut sandstone slab',
    'cyan banner',
    'cyan bed',
    'cyan candle',
    'cyan candle cake',
    'cyan carpet',
    'cyan concrete',
    'cyan concrete powder',
    'cyan glazed terracotta',
    'cyan shulker box',
    'cyan stained glass',
    'cyan stained glass pane',
    'cyan terracotta',
    'cyan wall banner',
    'cyan wool',
    'damaged anvil',
    'dandelion',
    'dark oak button',
    'dark oak door',
    'dark oak fence',
    'dark oak fence gate',
    'dark oak hanging sign',
    'dark oak leaves',
    'dark oak log',
    'dark oak planks',
    'dark oak pressure plate',
    'dark oak sapling',
    'dark oak shelf',
    'dark oak sign',
    'dark oak slab',
    'dark oak stairs',
    'dark oak trapdoor',
    'dark oak wall hanging sign',
    'dark oak wall sign',
    'dark oak wood',
    'dark prismarine',
    'dark prismarine slab',
    'dark prismarine stairs',
    'daylight detector',
    'dead brain coral',
    'dead brain coral block',
    'dead brain coral fan',
    'dead brain coral wall fan',
    'dead bubble coral',
    'dead bubble coral block',
    'dead bubble coral fan',
    'dead bubble coral wall fan',
    'dead bush',
    'dead fire coral',
    'dead fire coral block',
    'dead fire coral fan',
    'dead fire coral wall fan',
    'dead horn coral',
    'dead horn coral block',
    'dead horn coral fan',
    'dead horn coral wall fan',
    'dead tube coral',
    'dead tube coral block',
    'dead tube coral fan',
    'dead tube coral wall fan',
    'decorated pot',
    'deepslate',
    'deepslate brick slab',
    'deepslate brick stairs',
    'deepslate brick wall',
    'deepslate bricks',
    'deepslate coal ore',
    'deepslate copper ore',
    'deepslate diamond ore',
    'deepslate emerald ore',
    'deepslate gold ore',
    'deepslate iron ore',
    'deepslate lapis ore',
    'deepslate redstone ore',
    'deepslate tile slab',
    'deepslate tile stairs',
    'deepslate tile wall',
    'deepslate tiles',
    'detector rail',
    'diamond block',
    'diamond ore',
    'diorite',
    'diorite slab',
    'diorite stairs',
    'diorite wall',
    'dirt',
    'dirt path',
    'dispenser',
    'dragon egg',
    'dragon head',
    'dragon wall head',
    'dried ghast',
    'dried kelp block',
    'dripstone block',
    'dropper',
    'emerald block',
    'emerald ore',
    'enchanting table',
    'end gateway',
    'end portal',
    'end portal frame',
    'end rod',
    'end stone',
    'end stone brick slab',
    'end stone brick stairs',
    'end stone brick wall',
    'end stone bricks',
    'ender chest',
    'exposed chiseled copper',
    'exposed copper',
    'exposed copper bars',
    'exposed copper bulb',
    'exposed copper chain',
    'exposed copper chest',
    'exposed copper door',
    'exposed copper golem statue',
    'exposed copper grate',
    'exposed copper lantern',
    'exposed copper trapdoor',
    'exposed cut copper',
    'exposed cut copper slab',
    'exposed cut copper stairs',
    'exposed lightning rod',
    'farmland',
    'fern',
    'fire',
    'fire coral',
    'fire coral block',
    'fire coral fan',
    'fire coral wall fan',
    'firefly bush',
    'fletching table',
    'flower pot',
    'flowering azalea',
    'flowering azalea leaves',
    'frogspawn',
    'frosted ice',
    'furnace',
    'gilded blackstone',
    'glass',
    'glass pane',
    'glow lichen',
    'glowstone',
    'gold block',
    'gold ore',
    'golden dandelion',
    'granite',
    'granite slab',
    'granite stairs',
    'granite wall',
    'grass block',
    'gravel',
    'gray banner',
    'gray bed',
    'gray candle',
    'gray candle cake',
    'gray carpet',
    'gray concrete',
    'gray concrete powder',
    'gray glazed terracotta',
    'gray shulker box',
    'gray stained glass',
    'gray stained glass pane',
    'gray terracotta',
    'gray wall banner',
    'gray wool',
    'green banner',
    'green bed',
    'green candle',
    'green candle cake',
    'green carpet',
    'green concrete',
    'green concrete powder',
    'green glazed terracotta',
    'green shulker box',
    'green stained glass',
    'green stained glass pane',
    'green terracotta',
    'green wall banner',
    'green wool',
    'grindstone',
    'hanging roots',
    'hay block',
    'heavy core',
    'heavy weighted pressure plate',
    'honey block',
    'honeycomb block',
    'hopper',
    'horn coral',
    'horn coral block',
    'horn coral fan',
    'horn coral wall fan',
    'ice',
    'infested chiseled stone bricks',
    'infested cobblestone',
    'infested cracked stone bricks',
    'infested deepslate',
    'infested mossy stone bricks',
    'infested stone',
    'infested stone bricks',
    'iron bars',
    'iron block',
    'iron chain',
    'iron door',
    'iron ore',
    'iron trapdoor',
    'jack o lantern',
    'jigsaw',
    'jukebox',
    'jungle button',
    'jungle door',
    'jungle fence',
    'jungle fence gate',
    'jungle hanging sign',
    'jungle leaves',
    'jungle log',
    'jungle planks',
    'jungle pressure plate',
    'jungle sapling',
    'jungle shelf',
    'jungle sign',
    'jungle slab',
    'jungle stairs',
    'jungle trapdoor',
    'jungle wall hanging sign',
    'jungle wall sign',
    'jungle wood',
    'kelp',
    'kelp plant',
    'ladder',
    'lantern',
    'lapis block',
    'lapis ore',
    'large amethyst bud',
    'large fern',
    'lava',
    'lava cauldron',
    'leaf litter',
    'lectern',
    'lever',
    'light',
    'light blue banner',
    'light blue bed',
    'light blue candle',
    'light blue candle cake',
    'light blue carpet',
    'light blue concrete',
    'light blue concrete powder',
    'light blue glazed terracotta',
    'light blue shulker box',
    'light blue stained glass',
    'light blue stained glass pane',
    'light blue terracotta',
    'light blue wall banner',
    'light blue wool',
    'light gray banner',
    'light gray bed',
    'light gray candle',
    'light gray candle cake',
    'light gray carpet',
    'light gray concrete',
    'light gray concrete powder',
    'light gray glazed terracotta',
    'light gray shulker box',
    'light gray stained glass',
    'light gray stained glass pane',
    'light gray terracotta',
    'light gray wall banner',
    'light gray wool',
    'light weighted pressure plate',
    'lightning rod',
    'lilac',
    'lily of the valley',
    'lily pad',
    'lime banner',
    'lime bed',
    'lime candle',
    'lime candle cake',
    'lime carpet',
    'lime concrete',
    'lime concrete powder',
    'lime glazed terracotta',
    'lime shulker box',
    'lime stained glass',
    'lime stained glass pane',
    'lime terracotta',
    'lime wall banner',
    'lime wool',
    'lodestone',
    'loom',
    'magenta banner',
    'magenta bed',
    'magenta candle',
    'magenta candle cake',
    'magenta carpet',
    'magenta concrete',
    'magenta concrete powder',
    'magenta glazed terracotta',
    'magenta shulker box',
    'magenta stained glass',
    'magenta stained glass pane',
    'magenta terracotta',
    'magenta wall banner',
    'magenta wool',
    'magma block',
    'mangrove button',
    'mangrove door',
    'mangrove fence',
    'mangrove fence gate',
    'mangrove hanging sign',
    'mangrove leaves',
    'mangrove log',
    'mangrove planks',
    'mangrove pressure plate',
    'mangrove propagule',
    'mangrove roots',
    'mangrove shelf',
    'mangrove sign',
    'mangrove slab',
    'mangrove stairs',
    'mangrove trapdoor',
    'mangrove wall hanging sign',
    'mangrove wall sign',
    'mangrove wood',
    'medium amethyst bud',
    'melon',
    'melon stem',
    'moss block',
    'moss carpet',
    'mossy cobblestone',
    'mossy cobblestone slab',
    'mossy cobblestone stairs',
    'mossy cobblestone wall',
    'mossy stone brick slab',
    'mossy stone brick stairs',
    'mossy stone brick wall',
    'mossy stone bricks',
    'moving piston',
    'mud',
    'mud brick slab',
    'mud brick stairs',
    'mud brick wall',
    'mud bricks',
    'muddy mangrove roots',
    'mushroom stem',
    'mycelium',
    'nether brick fence',
    'nether brick slab',
    'nether brick stairs',
    'nether brick wall',
    'nether gold ore',
    'nether portal',
    'nether quartz ore',
    'nether sprouts',
    'nether wart',
    'nether wart block',
    'netherite block',
    'netherrack',
    'note block',
    'oak button',
    'oak door',
    'oak fence',
    'oak fence gate',
    'oak hanging sign',
    'oak leaves',
    'oak log',
    'oak planks',
    'oak pressure plate',
    'oak sapling',
    'oak shelf',
    'oak sign',
    'oak slab',
    'oak stairs',
    'oak trapdoor',
    'oak wall hanging sign',
    'oak wall sign',
    'oak wood',
    'observer',
    'obsidian',
    'ochre froglight',
    'open eyeblossom',
    'orange banner',
    'orange bed',
    'orange candle',
    'orange candle cake',
    'orange carpet',
    'orange concrete',
    'orange concrete powder',
    'orange glazed terracotta',
    'orange shulker box',
    'orange stained glass',
    'orange stained glass pane',
    'orange terracotta',
    'orange tulip',
    'orange wall banner',
    'orange wool',
    'oxeye daisy',
    'oxidized chiseled copper',
    'oxidized copper',
    'oxidized copper bars',
    'oxidized copper bulb',
    'oxidized copper chain',
    'oxidized copper chest',
    'oxidized copper door',
    'oxidized copper golem statue',
    'oxidized copper grate',
    'oxidized copper lantern',
    'oxidized copper trapdoor',
    'oxidized cut copper',
    'oxidized cut copper slab',
    'oxidized cut copper stairs',
    'oxidized lightning rod',
    'packed ice',
    'packed mud',
    'pale hanging moss',
    'pale moss block',
    'pale moss carpet',
    'pale oak button',
    'pale oak door',
    'pale oak fence',
    'pale oak fence gate',
    'pale oak hanging sign',
    'pale oak leaves',
    'pale oak log',
    'pale oak planks',
    'pale oak pressure plate',
    'pale oak sapling',
    'pale oak shelf',
    'pale oak sign',
    'pale oak slab',
    'pale oak stairs',
    'pale oak trapdoor',
    'pale oak wall hanging sign',
    'pale oak wall sign',
    'pale oak wood',
    'pearlescent froglight',
    'peony',
    'petrified oak slab',
    'piglin head',
    'piglin wall head',
    'pink banner',
    'pink bed',
    'pink candle',
    'pink candle cake',
    'pink carpet',
    'pink concrete',
    'pink concrete powder',
    'pink glazed terracotta',
    'pink petals',
    'pink shulker box',
    'pink stained glass',
    'pink stained glass pane',
    'pink terracotta',
    'pink tulip',
    'pink wall banner',
    'pink wool',
    'piston',
    'piston head',
    'pitcher crop',
    'pitcher plant',
    'player head',
    'player wall head',
    'podzol',
    'pointed dripstone',
    'polished andesite',
    'polished andesite slab',
    'polished andesite stairs',
    'polished basalt',
    'polished blackstone',
    'polished blackstone brick slab',
    'polished blackstone brick stairs',
    'polished blackstone brick wall',
    'polished blackstone bricks',
    'polished blackstone button',
    'polished blackstone pressure plate',
    'polished blackstone slab',
    'polished blackstone stairs',
    'polished blackstone wall',
    'polished deepslate',
    'polished deepslate slab',
    'polished deepslate stairs',
    'polished deepslate wall',
    'polished diorite',
    'polished diorite slab',
    'polished diorite stairs',
    'polished granite',
    'polished granite slab',
    'polished granite stairs',
    'polished tuff',
    'polished tuff slab',
    'polished tuff stairs',
    'polished tuff wall',
    'poppy',
    'potatoes',
    'potted acacia sapling',
    'potted allium',
    'potted azalea bush',
    'potted azure bluet',
    'potted bamboo',
    'potted birch sapling',
    'potted blue orchid',
    'potted brown mushroom',
    'potted cactus',
    'potted cherry sapling',
    'potted closed eyeblossom',
    'potted cornflower',
    'potted crimson fungus',
    'potted crimson roots',
    'potted dandelion',
    'potted dark oak sapling',
    'potted dead bush',
    'potted fern',
    'potted flowering azalea bush',
    'potted golden dandelion',
    'potted jungle sapling',
    'potted lily of the valley',
    'potted mangrove propagule',
    'potted oak sapling',
    'potted open eyeblossom',
    'potted orange tulip',
    'potted oxeye daisy',
    'potted pale oak sapling',
    'potted pink tulip',
    'potted poppy',
    'potted red mushroom',
    'potted red tulip',
    'potted spruce sapling',
    'potted torchflower',
    'potted warped fungus',
    'potted warped roots',
    'potted white tulip',
    'potted wither rose',
    'powder snow',
    'powder snow cauldron',
    'powered rail',
    'prismarine',
    'prismarine brick slab',
    'prismarine brick stairs',
    'prismarine bricks',
    'prismarine slab',
    'prismarine stairs',
    'prismarine wall',
    'pumpkin',
    'pumpkin stem',
    'purple banner',
    'purple bed',
    'purple candle',
    'purple candle cake',
    'purple carpet',
    'purple concrete',
    'purple concrete powder',
    'purple glazed terracotta',
    'purple shulker box',
    'purple stained glass',
    'purple stained glass pane',
    'purple terracotta',
    'purple wall banner',
    'purple wool',
    'purpur block',
    'purpur pillar',
    'purpur slab',
    'purpur stairs',
    'quartz block',
    'quartz bricks',
    'quartz pillar',
    'quartz slab',
    'quartz stairs',
    'rail',
    'raw copper block',
    'raw gold block',
    'raw iron block',
    'red banner',
    'red bed',
    'red candle',
    'red candle cake',
    'red carpet',
    'red concrete',
    'red concrete powder',
    'red glazed terracotta',
    'red mushroom',
    'red mushroom block',
    'red nether brick slab',
    'red nether brick stairs',
    'red nether brick wall',
    'red nether bricks',
    'red sand',
    'red sandstone',
    'red sandstone slab',
    'red sandstone stairs',
    'red sandstone wall',
    'red shulker box',
    'red stained glass',
    'red stained glass pane',
    'red terracotta',
    'red tulip',
    'red wall banner',
    'red wool',
    'redstone block',
    'redstone lamp',
    'redstone ore',
    'redstone torch',
    'redstone wall torch',
    'redstone wire',
    'reinforced deepslate',
    'repeater',
    'repeating command block',
    'resin block',
    'resin brick slab',
    'resin brick stairs',
    'resin brick wall',
    'resin clump',
    'respawn anchor',
    'rooted dirt',
    'rose bush',
    'sand',
    'sandstone',
    'sandstone slab',
    'sandstone stairs',
    'sandstone wall',
    'scaffolding',
    'sculk',
    'sculk catalyst',
    'sculk sensor',
    'sculk shrieker',
    'sculk vein',
    'sea lantern',
    'sea pickle',
    'seagrass',
    'short dry grass',
    'short grass',
    'shroomlight',
    'shulker box',
    'skeleton skull',
    'skeleton wall skull',
    'slime block',
    'small amethyst bud',
    'small dripleaf',
    'smithing table',
    'smoker',
    'smooth basalt',
    'smooth quartz',
    'smooth quartz slab',
    'smooth quartz stairs',
    'smooth red sandstone',
    'smooth red sandstone slab',
    'smooth red sandstone stairs',
    'smooth sandstone',
    'smooth sandstone slab',
    'smooth sandstone stairs',
    'smooth stone',
    'smooth stone slab',
    'sniffer egg',
    'snow',
    'snow block',
    'soul campfire',
    'soul fire',
    'soul lantern',
    'soul sand',
    'soul soil',
    'soul torch',
    'soul wall torch',
    'spawner',
    'sponge',
    'spore blossom',
    'spruce button',
    'spruce door',
    'spruce fence',
    'spruce fence gate',
    'spruce hanging sign',
    'spruce leaves',
    'spruce log',
    'spruce planks',
    'spruce pressure plate',
    'spruce sapling',
    'spruce shelf',
    'spruce sign',
    'spruce slab',
    'spruce stairs',
    'spruce trapdoor',
    'spruce wall hanging sign',
    'spruce wall sign',
    'spruce wood',
    'sticky piston',
    'stone',
    'stone brick slab',
    'stone brick stairs',
    'stone brick wall',
    'stone bricks',
    'stone button',
    'stone pressure plate',
    'stone slab',
    'stone stairs',
    'stonecutter',
    'stripped acacia log',
    'stripped acacia wood',
    'stripped bamboo block',
    'stripped birch log',
    'stripped birch wood',
    'stripped cherry log',
    'stripped cherry wood',
    'stripped crimson hyphae',
    'stripped crimson stem',
    'stripped dark oak log',
    'stripped dark oak wood',
    'stripped jungle log',
    'stripped jungle wood',
    'stripped mangrove log',
    'stripped mangrove wood',
    'stripped oak log',
    'stripped oak wood',
    'stripped pale oak log',
    'stripped pale oak wood',
    'stripped spruce log',
    'stripped spruce wood',
    'stripped warped hyphae',
    'stripped warped stem',
    'structure block',
    'structure void',
    'sugar cane',
    'sunflower',
    'suspicious gravel',
    'suspicious sand',
    'sweet berry bush',
    'tall dry grass',
    'tall grass',
    'tall seagrass',
    'target',
    'terracotta',
    'test block',
    'test instance block',
    'tinted glass',
    'torch',
    'torchflower',
    'torchflower crop',
    'trapped chest',
    'trial spawner',
    'tripwire',
    'tripwire hook',
    'tube coral',
    'tube coral block',
    'tube coral fan',
    'tube coral wall fan',
    'tuff',
    'tuff brick slab',
    'tuff brick stairs',
    'tuff brick wall',
    'tuff bricks',
    'tuff slab',
    'tuff stairs',
    'tuff wall',
    'turtle egg',
    'twisting vines',
    'twisting vines plant',
    'vault',
    'verdant froglight',
    'vine',
    'void air',
    'wall torch',
    'warped button',
    'warped door',
    'warped fence',
    'warped fence gate',
    'warped fungus',
    'warped hanging sign',
    'warped hyphae',
    'warped nylium',
    'warped planks',
    'warped pressure plate',
    'warped roots',
    'warped shelf',
    'warped sign',
    'warped slab',
    'warped stairs',
    'warped stem',
    'warped trapdoor',
    'warped wall hanging sign',
    'warped wall sign',
    'warped wart block',
    'water',
    'water cauldron',
    'waxed chiseled copper',
    'waxed copper bars',
    'waxed copper block',
    'waxed copper bulb',
    'waxed copper chain',
    'waxed copper chest',
    'waxed copper door',
    'waxed copper golem statue',
    'waxed copper grate',
    'waxed copper lantern',
    'waxed copper trapdoor',
    'waxed cut copper',
    'waxed cut copper slab',
    'waxed cut copper stairs',
    'waxed exposed chiseled copper',
    'waxed exposed copper',
    'waxed exposed copper bars',
    'waxed exposed copper bulb',
    'waxed exposed copper chain',
    'waxed exposed copper chest',
    'waxed exposed copper door',
    'waxed exposed copper golem statue',
    'waxed exposed copper grate',
    'waxed exposed copper lantern',
    'waxed exposed copper trapdoor',
    'waxed exposed cut copper',
    'waxed exposed cut copper slab',
    'waxed exposed cut copper stairs',
    'waxed exposed lightning rod',
    'waxed lightning rod',
    'waxed oxidized chiseled copper',
    'waxed oxidized copper',
    'waxed oxidized copper bars',
    'waxed oxidized copper bulb',
    'waxed oxidized copper chain',
    'waxed oxidized copper chest',
    'waxed oxidized copper door',
    'waxed oxidized copper golem statue',
    'waxed oxidized copper grate',
    'waxed oxidized copper lantern',
    'waxed oxidized copper trapdoor',
    'waxed oxidized cut copper',
    'waxed oxidized cut copper slab',
    'waxed oxidized cut copper stairs',
    'waxed oxidized lightning rod',
    'waxed weathered chiseled copper',
    'waxed weathered copper',
    'waxed weathered copper bars',
    'waxed weathered copper bulb',
    'waxed weathered copper chain',
    'waxed weathered copper chest',
    'waxed weathered copper door',
    'waxed weathered copper golem statue',
    'waxed weathered copper grate',
    'waxed weathered copper lantern',
    'waxed weathered copper trapdoor',
    'waxed weathered cut copper',
    'waxed weathered cut copper slab',
    'waxed weathered cut copper stairs',
    'waxed weathered lightning rod',
    'weathered chiseled copper',
    'weathered copper',
    'weathered copper bars',
    'weathered copper bulb',
    'weathered copper chain',
    'weathered copper chest',
    'weathered copper door',
    'weathered copper golem statue',
    'weathered copper grate',
    'weathered copper lantern',
    'weathered copper trapdoor',
    'weathered cut copper',
    'weathered cut copper slab',
    'weathered cut copper stairs',
    'weathered lightning rod',
    'weeping vines',
    'weeping vines plant',
    'wet sponge',
    'wheat',
    'white banner',
    'white bed',
    'white candle',
    'white candle cake',
    'white carpet',
    'white concrete',
    'white concrete powder',
    'white glazed terracotta',
    'white shulker box',
    'white stained glass',
    'white stained glass pane',
    'white terracotta',
    'white tulip',
    'white wall banner',
    'white wool',
    'wildflowers',
    'wither rose',
    'wither skeleton skull',
    'wither skeleton wall skull',
    'yellow banner',
    'yellow bed',
    'yellow candle',
    'yellow candle cake',
    'yellow carpet',
    'yellow concrete',
    'yellow concrete powder',
    'yellow glazed terracotta',
    'yellow shulker box',
    'yellow stained glass',
    'yellow stained glass pane',
    'yellow terracotta',
    'yellow wall banner',
    'yellow wool',
    'zombie head',
    'zombie wall head',
  ],
}
