import type { SkriptType } from './Types'

export const ParticleEffects: SkriptType = {
  name: 'particle_effect',
  options: [
    'angry villager',
    'ash',
    'block',
    'block crumble',
    'block marker',
    'bubble',
    'bubble column up',
    'bubble pop',
    'campfire cosy smoke',
    'campfire signal smoke',
    'cherry leaves',
    'cloud',
    'composter',
    'copper fire flame',
    'crimson spore',
    'crit',
    'current down',
    'damage indicator',
    'dolphin',
    'dragon breath',
    'dripping dripstone lava',
    'dripping dripstone water',
    'dripping honey',
    'dripping lava',
    'dripping obsidian tear',
    'dripping water',
    'dust',
    'dust color transition',
    'dust pillar',
    'dust plume',
    'effect',
    'egg crack',
    'elder guardian',
    'electric spark',
    'enchant',
    'enchanted hit',
    'end rod',
    'entity effect',
    'explosion',
    'explosion emitter',
    'falling dripstone lava',
    'falling dripstone water',
    'falling dust',
    'falling honey',
    'falling lava',
    'falling nectar',
    'falling obsidian tear',
    'falling spore blossom',
    'falling water',
    'firefly',
    'firework',
    'fishing',
    'flame',
    'flash',
    'glow',
    'glow squid ink',
    'gust',
    'gust emitter large',
    'gust emitter small',
    'happy villager',
    'heart',
    'infested',
    'instant effect',
    'item',
    'item cobweb',
    'item slime',
    'item snowball',
    'landing honey',
    'landing lava',
    'landing obsidian tear',
    'large smoke',
    'lava',
    'mycelium',
    'nautilus',
    'note',
    'ominous spawning',
    'pale oak leaves',
    'pause mob growth',
    'poof',
    'portal',
    'raid omen',
    'rain',
    'reset mob growth',
    'reverse portal',
    'scrape',
    'sculk charge',
    'sculk charge pop',
    'sculk soul',
    'shriek',
    'small flame',
    'small gust',
    'smoke',
    'sneeze',
    'snowflake',
    'sonic boom',
    'soul',
    'soul fire flame',
    'spit',
    'splash',
    'spore blossom air',
    'squid ink',
    'sweep attack',
    'tinted leaves',
    'totem of undying',
    'trail',
    'trial omen',
    'trial spawner detection',
    'trial spawner detection ominous',
    'underwater',
    'vault connection',
    'vibration',
    'warped spore',
    'wax off',
    'wax on',
    'white ash',
    'white smoke',
    'witch',
  ],
}
