import * as Blockly from 'blockly/core'
import { FieldGridDropdown } from '@blockly/field-grid-dropdown'
import { t } from '@/locales/i18n'

export function createPotionEffectTypeFieldDropdown() {
  const options: Blockly.MenuOption[] = [
    [t('SKRIPT_POTION_EFFECT_TYPE_ABSORPTION'), 'absorption'],
    [t('SKRIPT_POTION_EFFECT_TYPE_BAD_LUCK'), 'bad luck'],
    [t('SKRIPT_POTION_EFFECT_TYPE_BAD_OMEN'), 'bad omen'],
    [t('SKRIPT_POTION_EFFECT_TYPE_BLINDNESS'), 'blindsight'],
    [t('SKRIPT_POTION_EFFECT_TYPE_CONDUIT_POWER'), 'conduit power'],
    [t('SKRIPT_POTION_EFFECT_TYPE_CONFUSION'), 'confusion'],
    [t('SKRIPT_POTION_EFFECT_TYPE_DAMAGE'), 'damage'],
    [t('SKRIPT_POTION_EFFECT_TYPE_DAMAGE_RESISTANCE'), 'damage resistance'],
    [t('SKRIPT_POTION_EFFECT_TYPE_DARKNESS'), 'darkness'],
    [t('SKRIPT_POTION_EFFECT_TYPE_DOLPHINS_GRACE'), "dolphin's grace"],
    [t('SKRIPT_POTION_EFFECT_TYPE_FAST_DIGGING'), 'fast digging'],
    [t('SKRIPT_POTION_EFFECT_TYPE_FAST_MINING'), 'fast mining'],
    [t('SKRIPT_POTION_EFFECT_TYPE_FIRE_IMMUNITY'), 'fire immunity'],
    [t('SKRIPT_POTION_EFFECT_TYPE_FIRE_RESISTANCE'), 'fire resistance'],
    [t('SKRIPT_POTION_EFFECT_TYPE_FLOATING'), 'floating'],
    [t('SKRIPT_POTION_EFFECT_TYPE_GLOWING'), 'glowing'],
    [t('SKRIPT_POTION_EFFECT_TYPE_HEALTH'), 'health'],
    [t('SKRIPT_POTION_EFFECT_TYPE_HEALTH_BOOST'), 'health boost'],
    [t('SKRIPT_POTION_EFFECT_TYPE_HERO_OF_THE_VILLAGE'), 'hero of the village'],
    [t('SKRIPT_POTION_EFFECT_TYPE_HUNGER'), 'hunger'],
    [t('SKRIPT_POTION_EFFECT_TYPE_INCREASE_DAMAGE'), 'increase damage'],
    [t('SKRIPT_POTION_EFFECT_TYPE_INCREASED_DAMAGE'), 'increased damage'],
    [t('SKRIPT_POTION_EFFECT_TYPE_INFESTED'), 'infested'],
    [t('SKRIPT_POTION_EFFECT_TYPE_INSTANT_DAMAGE'), 'instant damage'],
    [t('SKRIPT_POTION_EFFECT_TYPE_INSTANT_HEALTH'), 'instant health'],
    [t('SKRIPT_POTION_EFFECT_TYPE_INVISIBILITY'), 'invisibility'],
    [t('SKRIPT_POTION_EFFECT_TYPE_JUMP'), 'jump'],
    [t('SKRIPT_POTION_EFFECT_TYPE_JUMP_BOOST'), 'jump boost'],
    [t('SKRIPT_POTION_EFFECT_TYPE_LEVITATION'), 'levitation'],
    [t('SKRIPT_POTION_EFFECT_TYPE_LUCK'), 'luck'],
    [t('SKRIPT_POTION_EFFECT_TYPE_MAX_HEALTH_BOOST'), 'max health boost'],
    [t('SKRIPT_POTION_EFFECT_TYPE_MAXIMUM_HEALTH_BOOST'), 'maximum health boost'],
    [t('SKRIPT_POTION_EFFECT_TYPE_MINING_FATIGUE'), 'mining fatigue'],
    [t('SKRIPT_POTION_EFFECT_TYPE_NAUSEA'), 'nausea'],
    [t('SKRIPT_POTION_EFFECT_TYPE_NIGHT_VISION'), 'night vision'],
    [t('SKRIPT_POTION_EFFECT_TYPE_OOZING'), 'oozing'],
    [t('SKRIPT_POTION_EFFECT_TYPE_POISON'), 'poison'],
    [t('SKRIPT_POTION_EFFECT_TYPE_RAID_OMEN'), 'raid omen'],
    [t('SKRIPT_POTION_EFFECT_TYPE_REDUCE_DAMAGE'), 'reduce damage'],
    [t('SKRIPT_POTION_EFFECT_TYPE_REDUCED_DAMAGE'), 'reduced damage'],
    [t('SKRIPT_POTION_EFFECT_TYPE_REGENERATION'), 'regeneration'],
    [t('SKRIPT_POTION_EFFECT_TYPE_RESISTANCE'), 'resistance'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SATURATION'), 'saturation'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SLOW'), 'slow'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SLOW_DIGGING'), 'slow digging'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SLOW_FALL'), 'slow fall'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SLOW_FALLING'), 'slow falling'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SLOW_MINING'), 'slow mining'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SLOWNESS'), 'slowness'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SPEED'), 'speed'],
    [t('SKRIPT_POTION_EFFECT_TYPE_STRENGTH'), 'strength'],
    [t('SKRIPT_POTION_EFFECT_TYPE_SWIFTNESS'), 'swiftness'],
    [t('SKRIPT_POTION_EFFECT_TYPE_TRIAL_OMEN'), 'trial omen'],
    [t('SKRIPT_POTION_EFFECT_TYPE_UNLUCK'), 'unluck'],
    [t('SKRIPT_POTION_EFFECT_TYPE_WATER_BREATHING'), 'water breathing'],
    [t('SKRIPT_POTION_EFFECT_TYPE_WEAKNESS'), 'weakness'],
    [t('SKRIPT_POTION_EFFECT_TYPE_WEAVING'), 'weaving'],
    [t('SKRIPT_POTION_EFFECT_TYPE_WIND_CHARGED'), 'wind charged'],
    [t('SKRIPT_POTION_EFFECT_TYPE_WITHER'), 'wither'],
    [t('SKRIPT_POTION_EFFECT_TYPE_WITHER_EFFECT'), 'wither effect'],
    [t('SKRIPT_POTION_EFFECT_TYPE_WITHER_POTION_EFFECT'), 'wither potion effect'],
  ]
  return new FieldGridDropdown(options)
}
