import type { SkriptType } from './Types'

export const PotionEffectTypes: SkriptType = {
  name: 'potion_effect_type',
  options: [
    'speed',
    'slowness',
    'haste',
    'mining fatigue',
    'strength',
    'instant health',
    'instant damage',
    'jump boost',
    'nausea',
    'regeneration',
    'resistance',
    'fire resistance',
    'water breathing',
    'invisibility',
    'blindness',
    'night vision',
    'hunger',
    'weakness',
    'poison',
    'wither',
    'health boost',
    'absorption',
    'saturation',
    'luck',
    'unluck',
    'levitation',
    'glowing',
    'slow falling',
    'dolphins grace',
    'conduit power',
    'bad omen',
    'hero of the village',
    'darkness',
    'wind charged',
    'raid omen',
    'infested',
    'weaving',
    'trial omen',
    'oozing',
    'breath of the nautilus',
  ],
}

export const PotionEffectTypeCategories: SkriptType = {
  name: 'potion_effect_type_category',
  options: ['beneficial', 'harmful', 'neutral'],
}
