import type { SkriptType } from './Types'

export const SpawnReasons: SkriptType = {
  name: 'spawn_reason',
  options: [
    'bed',
    'beehive',
    'breeding',
    'bucket',
    'build irongolem',
    'build snowman',
    'build wither',
    'chunk gen',
    'command',
    'cured',
    'custom',
    'default',
    'dispense egg',
    'drowned',
    'duplication',
    'egg',
    'ender pearl',
    'explosion',
    'frozen',
    'infection',
    'jockey',
    'lightning',
    'metamorphosis',
    'mount',
    'natural',
    'nether portal',
    'ocelot baby',
    'ominous item spawner',
    'patrol',
    'piglin zombified',
    'potion effect',
    'raid',
    'reinforcements',
    'sheared',
    'shoulder entity',
    'silverfish block',
    'slime split',
    'spawner',
    'spawner egg',
    'spell',
    'trap',
    'village defense',
    'village invasion',
    'trial spawner',
    'enchantment',
    'rehydration',
    'build coppergolem',
  ],
}
