// Vault Display Item 和 Villager Career Change 居然没文档
export const SkriptSimpleEvents: string[] = [
  'chunk_generate',
  'ignition',
  'creeper_power',
  'spread',
  'zombie_break_door',
  'combust',
  'explode',
  'slime_split',
  'bucket_fill',
  'leaves_decay',
  'piston_extend',
  'piston_retract',
  'tame',
  'redstone',
  'lightning_strike',
  'quit',
  'vehicle_create',
  'shoot',
  'vehicle_damage',
  'vehicle_enter',
  'spawn_change',
  'inventory_close',
  'resurrect_attempt',
  'vehicle_exit',
  'inventory_open',
  'player_world_change',
  'sneak_toggle',
  'bed_leave',
  'connect',
  'jump',
  'entity_dismount',
  'hand_item_swap',
  'chunk_unload',
  'item_damage',
  'sponge_absorb',
  'enchant',
  'item_mend',
  'block_fertilize',
  'block_damage',
  'chat',
  'can_build_check',
  'language_change',
  'flight_toggle',
  'gliding_state_change',
  'entity_mount',
  'hunger_meter_change',
  'join',
  'sheep_regrow_wool',
  'swim_toggle',
  'projectile_collide',
  'broadcast',
  'piglin_barter',
  'anvil_damage',
  'chunk_load',
  'anvil_prepare',
  'arm_swing',
  'bed_enter',
  'aoe_cloud_effect',
  'bucket_empty',
  'flow',
  'player_deep_sleep',
  'player_trade',
  'explosion_prime',
  'physics',
  'inventory_pickup',
  'inventory_slot_change',
  'inventory_drag',
  'kick',
  'horse_jump',
  'entity_jump',
  'vehicle_destroy',
  'server_list_ping',
  'respawn',
  'sprint_toggle',
  'tool_change',
  'riptide',
  'projectile_hit',
  'bat_toggle_sleep',
  'egg_throw',
  'player_pickup_arrow',
  'portal_enter',
  'ready_arrow',
  'stop_using_item',
  'bell_ring',
  'beacon_change_effect',
  'bell_resonate',
  'portal_create',
  'vehicle_move',
  'elytra_boost',
  'experience_cooldown_change',
  'pig_zap',
  'sign_change',
  'enderman_enrage',
  'item_break',
  'world_border_bounds_change',
  'world_border_bounds_finish_change',
  'world_border_center_change',
  'enchant_prepare',
  'vault_display_item',
  'villager_career_change',
] as const

// Player Chunk Enter
export const OhterSimpleEvents = ['first_join', 'loot_generate', 'book_edit', 'brewing_start', 'player_chunk_enter'] as const

export const SimpleEvents = [...SkriptSimpleEvents, ...OhterSimpleEvents] as const

export type SimpleEvent = (typeof SimpleEvents)[number]

export const SimpleEventSyntax: Record<SimpleEvent, string> = {} as const
export function generateCodeForSimpleEvent(event: SimpleEvent) {
  return SimpleEventSyntax[event] ?? `on ${event.replace(/_/g, ' ')}`
}
