'skript syntax'

import * as Blockly from 'blockly/core'
import { registerSimpleEvent } from './SkriptEventBlock'

type SimpleEventInfo = {
  key: string
  code?: string
  title: string
  eventValues: string[]
  cancellable: boolean
  docId: number
}

const SimpleEventInfos: SimpleEventInfo[] = [
  {
    key: 'can_build_check',
    title: 'Can Build Check',
    eventValues: ['event-block', 'event-location', 'event-player', 'event-world', 'past event-block'],
    cancellable: false,
    docId: 1012,
  },
  {
    key: 'block_damage',
    title: 'Block Damage',
    eventValues: ['event-block', 'event-location', 'event-player', 'event-world'],
    cancellable: true,
    docId: 1013,
  },
  {
    key: 'flow',
    title: 'Flow',
    eventValues: ['event-block', 'event-location', 'event-world', 'future event-block'],
    cancellable: true,
    docId: 1014,
  },
  {
    key: 'ignition',
    title: 'Ignition',
    eventValues: ['event-block', 'event-location', 'event-player', 'event-world'],
    cancellable: true,
    docId: 1015,
  },
  {
    key: 'physics',
    title: 'Physics',
    eventValues: ['event-block', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1016,
  },
  {
    key: 'piston_extend',
    title: 'Piston Extend',
    eventValues: ['event-block', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1017,
  },
  {
    key: 'piston_retract',
    title: 'Piston Retract',
    eventValues: ['event-block', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1018,
  },
  {
    key: 'redstone',
    title: 'Redstone',
    eventValues: ['event-block', 'event-location', 'event-world'],
    cancellable: false,
    docId: 1019,
  },
  {
    key: 'spread',
    title: 'Spread',
    eventValues: ['event-block', 'event-location', 'event-world', 'past event-block'],
    cancellable: true,
    docId: 1020,
  },
  {
    key: 'chunk_load',
    title: 'Chunk Load',
    eventValues: ['event-chunk', 'event-world'],
    cancellable: false,
    docId: 1021,
  },
  {
    key: 'chunk_generate',
    title: 'Chunk Generate',
    eventValues: ['event-chunk', 'event-world'],
    cancellable: false,
    docId: 1022,
  },
  {
    key: 'chunk_unload',
    title: 'Chunk Unload',
    eventValues: ['event-chunk', 'event-world'],
    cancellable: false,
    docId: 1023,
  },
  {
    key: 'creeper_power',
    title: 'Creeper Power',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1024,
  },
  {
    key: 'zombie_break_door',
    title: 'Zombie Break Door',
    eventValues: ['event-block', 'event-block data', 'event-command sender', 'event-entity', 'event-location', 'event-world', 'future event-block data', 'past event-block'],
    cancellable: true,
    docId: 1025,
  },
  {
    key: 'combust',
    title: 'Combust',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1026,
  },
  {
    key: 'explode',
    title: 'Explode',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1027,
  },
  {
    key: 'portal_enter',
    title: 'Portal Enter',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1028,
  },
  {
    key: 'tame',
    title: 'Tame',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1030,
  },
  {
    key: 'explosion_prime',
    title: 'Explosion Prime',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1031,
  },
  {
    key: 'hunger_meter_change',
    title: 'Hunger Meter Change',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1032,
  },
  {
    key: 'leaves_decay',
    title: 'Leaves Decay',
    eventValues: ['event-block', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1035,
  },
  {
    key: 'lightning_strike',
    title: 'Lightning Strike',
    eventValues: ['event-entity', 'event-world'],
    cancellable: true,
    docId: 1036,
  },
  {
    key: 'pig_zap',
    title: 'Pig Zap',
    eventValues: ['event-command sender', 'event-entities', 'event-entity', 'event-location', 'event-transform reason', 'event-world'],
    cancellable: true,
    docId: 1037,
  },
  {
    key: 'bed_enter',
    title: 'Bed Enter',
    eventValues: ['event-block', 'event-player', 'event-world'],
    cancellable: true,
    docId: 1038,
  },
  {
    key: 'bed_leave',
    title: 'Bed Leave',
    eventValues: ['event-block', 'event-player', 'event-world'],
    cancellable: true,
    docId: 1039,
  },
  {
    key: 'bucket_empty',
    title: 'Bucket Empty',
    eventValues: ['event-block', 'event-player', 'event-world', 'past event-block'],
    cancellable: true,
    docId: 1040,
  },
  {
    key: 'bucket_fill',
    title: 'Bucket fill',
    eventValues: ['event-block', 'event-player', 'event-world', 'future event-block'],
    cancellable: true,
    docId: 1041,
  },
  {
    key: 'egg_throw',
    title: 'Egg Throw',
    eventValues: ['event-player', 'event-projectile', 'event-world'],
    cancellable: false,
    docId: 9452,
  },
  {
    key: 'item_break',
    code: 'tool break',
    title: 'Item Break',
    eventValues: ['event-item stack', 'event-player', 'event-world'],
    cancellable: false,
    docId: 1044,
  },
  {
    key: 'item_damage',
    title: 'Item Damage',
    eventValues: ['event-item stack', 'event-player', 'event-world'],
    cancellable: true,
    docId: 4167,
  },
  {
    key: 'tool_change',
    title: 'Tool Change',
    eventValues: ['event-player', 'event-slot', 'event-world', 'past event-slot'],
    cancellable: true,
    docId: 1045,
  },
  {
    key: 'join',
    title: 'Join',
    eventValues: ['event-player', 'event-world'],
    cancellable: false,
    docId: 1046,
  },
  {
    key: 'connect',
    title: 'Connect',
    eventValues: ['event-player', 'event-world'],
    cancellable: false,
    docId: 1047,
  },
  {
    key: 'kick',
    title: 'Kick',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 1048,
  },
  {
    key: 'quit',
    title: 'Quit',
    eventValues: ['event-player', 'event-quit reason', 'event-world'],
    cancellable: false,
    docId: 1051,
  },
  {
    key: 'respawn',
    title: 'Respawn',
    eventValues: ['event-player', 'event-world'],
    cancellable: false,
    docId: 1052,
  },
  {
    key: 'sneak_toggle',
    title: 'Sneak Toggle',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 1054,
  },
  {
    key: 'sprint_toggle',
    title: 'Sprint Toggle',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 1055,
  },
  {
    key: 'portal_create',
    title: 'Portal Create',
    eventValues: ['event-blocks', 'event-entity', 'event-world'],
    cancellable: true,
    docId: 1056,
  },
  {
    key: 'projectile_hit',
    title: 'Projectile Hit',
    eventValues: ['event-block', 'event-projectile'],
    cancellable: true,
    docId: 1057,
  },
  {
    key: 'projectile_collide',
    title: 'Projectile Collide',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-projectile', 'event-world'],
    cancellable: true,
    docId: 6345,
  },
  {
    key: 'shoot',
    title: 'Shoot',
    eventValues: ['event-projectile'],
    cancellable: true,
    docId: 1058,
  },
  {
    key: 'sign_change',
    title: 'Sign Change',
    eventValues: ['event-block', 'event-location', 'event-player', 'event-texts', 'event-world'],
    cancellable: true,
    docId: 1059,
  },
  {
    key: 'spawn_change',
    title: 'Spawn Change',
    eventValues: ['event-world'],
    cancellable: false,
    docId: 1060,
  },
  {
    key: 'vehicle_create',
    title: 'Vehicle Create',
    eventValues: ['event-entity', 'event-vehicle', 'event-world'],
    cancellable: true,
    docId: 1061,
  },
  {
    key: 'vehicle_damage',
    title: 'Vehicle Damage',
    eventValues: ['event-entity', 'event-vehicle', 'event-world'],
    cancellable: true,
    docId: 1062,
  },
  {
    key: 'vehicle_destroy',
    title: 'Vehicle Destroy',
    eventValues: ['event-entity', 'event-vehicle', 'event-world'],
    cancellable: true,
    docId: 1063,
  },
  {
    key: 'vehicle_enter',
    title: 'Vehicle Enter',
    eventValues: ['event-entity', 'event-vehicle', 'event-world'],
    cancellable: true,
    docId: 1064,
  },
  {
    key: 'vehicle_exit',
    title: 'Vehicle Exit',
    eventValues: ['event-entity', 'event-living entity', 'event-vehicle', 'event-world'],
    cancellable: true,
    docId: 1065,
  },
  {
    key: 'entity_mount',
    code: 'mount',
    title: 'Entity Mount',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1066,
  },
  {
    key: 'entity_dismount',
    code: 'dismount',
    title: 'Entity Dismount',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1067,
  },
  {
    key: 'gliding_state_change',
    title: 'Gliding State Change',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1072,
  },
  {
    key: 'aoe_cloud_effect',
    code: 'area cloud effect',
    title: 'AoE Cloud Effect',
    eventValues: ['event-command sender', 'event-entity', 'event-living entities', 'event-location', 'event-potion effect type', 'event-world'],
    cancellable: true,
    docId: 1073,
  },
  {
    key: 'sheep_regrow_wool',
    title: 'Sheep Regrow Wool',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 3257,
  },
  {
    key: 'inventory_open',
    title: 'Inventory Open',
    eventValues: ['event-inventory', 'event-player'],
    cancellable: true,
    docId: 1075,
  },
  {
    key: 'inventory_close',
    title: 'Inventory Close',
    eventValues: ['event-inventory', 'event-inventory close reason', 'event-player'],
    cancellable: false,
    docId: 1076,
  },
  {
    key: 'slime_split',
    title: 'Slime Split',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 1077,
  },
  {
    key: 'resurrect_attempt',
    title: 'Resurrect Attempt',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-slot', 'event-world'],
    cancellable: true,
    docId: 1078,
  },
  {
    key: 'player_world_change',
    title: 'Player World Change',
    eventValues: ['event-player', 'event-world', 'past event-world'],
    cancellable: false,
    docId: 1079,
  },
  {
    key: 'flight_toggle',
    title: 'Flight Toggle',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 2596,
  },
  {
    key: 'language_change',
    title: 'Language Change',
    eventValues: ['event-player', 'event-world'],
    cancellable: false,
    docId: 2819,
  },
  {
    key: 'jump',
    title: 'Jump',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 3010,
  },
  {
    key: 'hand_item_swap',
    code: 'swap hand items',
    title: 'Hand Item Swap',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 3009,
  },
  {
    key: 'server_list_ping',
    title: 'Server List Ping',
    eventValues: [],
    cancellable: true,
    docId: 3011,
  },
  {
    key: 'swim_toggle',
    title: 'Swim Toggle',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 3155,
  },
  {
    key: 'riptide',
    title: 'Riptide',
    eventValues: ['event-item stack', 'event-player', 'event-world'],
    cancellable: false,
    docId: 4168,
  },
  {
    key: 'sponge_absorb',
    title: 'Sponge Absorb',
    eventValues: ['event-block', 'event-location', 'event-world'],
    cancellable: true,
    docId: 4169,
  },
  {
    key: 'enchant_prepare',
    title: 'Enchant Prepare',
    eventValues: ['event-block', 'event-inventory', 'event-item stack', 'event-player'],
    cancellable: true,
    docId: 4262,
  },
  {
    key: 'enchant',
    title: 'Enchant',
    eventValues: ['event-block', 'event-enchantment types', 'event-inventory', 'event-item stack', 'event-player'],
    cancellable: true,
    docId: 4261,
  },
  {
    key: 'inventory_pickup',
    title: 'Inventory Pickup',
    eventValues: ['event-dropped item', 'event-inventory', 'event-item stack'],
    cancellable: true,
    docId: 4501,
  },
  {
    key: 'horse_jump',
    title: 'Horse Jump',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 4500,
  },
  {
    key: 'block_fertilize',
    title: 'Block Fertilize',
    eventValues: ['event-block', 'event-blocks', 'event-location', 'event-player', 'event-world'],
    cancellable: true,
    docId: 4285,
  },
  {
    key: 'arm_swing',
    title: 'Arm Swing',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 4498,
  },
  {
    key: 'item_mend',
    title: 'Item Mend',
    eventValues: ['event-entity', 'event-item stack', 'event-player', 'event-world'],
    cancellable: true,
    docId: 4502,
  },
  {
    key: 'anvil_prepare',
    title: 'Anvil Prepare',
    eventValues: ['event-inventory', 'event-item stack'],
    cancellable: false,
    docId: 9451,
  },
  {
    key: 'player_trade',
    title: 'Player Trade',
    eventValues: ['event-living entity', 'event-player', 'event-world'],
    cancellable: true,
    docId: 9460,
  },
  {
    key: 'entity_jump',
    title: 'Entity Jump',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 9453,
  },
  {
    key: 'anvil_damage',
    title: 'Anvil Damage',
    eventValues: ['event-inventory'],
    cancellable: true,
    docId: 9450,
  },
  {
    key: 'stop_using_item',
    title: 'Stop Using Item',
    eventValues: ['event-item type', 'event-player', 'event-time span', 'event-world'],
    cancellable: false,
    docId: 10130,
  },
  {
    key: 'ready_arrow',
    title: 'Ready Arrow',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 10127,
  },
  {
    key: 'inventory_slot_change',
    title: 'Inventory Slot Change',
    eventValues: ['event-item stack', 'event-player', 'event-slot', 'event-world', 'past event-item stack'],
    cancellable: false,
    docId: 9456,
  },
  {
    key: 'player_deep_sleep',
    title: 'Player Deep Sleep',
    eventValues: ['event-player', 'event-world'],
    cancellable: true,
    docId: 9459,
  },
  {
    key: 'player_pickup_arrow',
    title: 'Player Pickup Arrow',
    eventValues: ['event-dropped item', 'event-entity', 'event-item stack', 'event-player', 'event-projectile', 'event-world'],
    cancellable: true,
    docId: 10126,
  },
  {
    key: 'inventory_drag',
    title: 'Inventory Drag',
    eventValues: [
      'event-click type',
      'event-inventories',
      'event-inventory',
      'event-item stack',
      'event-item stacks',
      'event-player',
      'event-slots',
      'event-world',
      'past event-item stack',
    ],
    cancellable: true,
    docId: 9455,
  },
  {
    key: 'piglin_barter',
    title: 'Piglin Barter',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 12319,
  },
  {
    key: 'bell_ring',
    title: 'Bell Ring',
    eventValues: ['event-block', 'event-direction', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 11491,
  },
  {
    key: 'bell_resonate',
    title: 'Bell Resonate',
    eventValues: ['event-block', 'event-entities', 'event-location', 'event-world'],
    cancellable: false,
    docId: 11490,
  },
  {
    key: 'enderman_enrage',
    title: 'Enderman Enrage',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-player', 'event-world'],
    cancellable: true,
    docId: 11788,
  },
  {
    key: 'beacon_change_effect',
    title: 'Beacon Change Effect',
    eventValues: ['event-block', 'event-player', 'event-world'],
    cancellable: true,
    docId: 13239,
  },
  {
    key: 'broadcast',
    title: 'Broadcast',
    eventValues: [],
    cancellable: true,
    docId: 12315,
  },
  {
    key: 'experience_cooldown_change',
    title: 'Experience Cooldown Change',
    eventValues: ['event-experience cooldown change reason', 'event-player', 'event-time span', 'event-world', 'past event-time span'],
    cancellable: false,
    docId: 12317,
  },
  {
    key: 'vehicle_move',
    title: 'Vehicle Move',
    eventValues: ['event-entity', 'event-location', 'event-vehicle', 'event-world', 'past event-location'],
    cancellable: false,
    docId: 13241,
  },
  {
    key: 'elytra_boost',
    title: 'Elytra Boost',
    eventValues: ['event-entity', 'event-item stack', 'event-player', 'event-world'],
    cancellable: true,
    docId: 13240,
  },
  {
    key: 'bat_toggle_sleep',
    title: 'Bat Toggle Sleep',
    eventValues: ['event-command sender', 'event-entity', 'event-location', 'event-world'],
    cancellable: true,
    docId: 13317,
  },
  {
    key: 'world_border_bounds_change',
    title: 'World Border Bounds Change',
    eventValues: ['event-number', 'event-time span', 'event-world', 'event-worldborder', 'past event-number'],
    cancellable: true,
    docId: 13322,
  },
  {
    key: 'world_border_bounds_finish_change',
    title: 'World Border Bounds Finish Change',
    eventValues: ['event-number', 'event-time span', 'event-world', 'event-worldborder', 'past event-number'],
    cancellable: false,
    docId: 13323,
  },
  {
    key: 'world_border_center_change',
    title: 'World Border Center Change',
    eventValues: ['event-location', 'event-world', 'event-worldborder', 'past event-location'],
    cancellable: true,
    docId: 13324,
  },
  {
    key: 'vault_display_item',
    title: 'Vault Display Item',
    eventValues: [],
    cancellable: false,
    docId: 0,
  },
  {
    key: 'villager_career_change',
    title: 'Villager Career Change',
    eventValues: [],
    cancellable: false,
    docId: 0,
  },
]

export function registerAll(): Blockly.utils.toolbox.BlockInfo[] {
  return SimpleEventInfos.map((info) => {
    return registerSimpleEvent({
      title: info.title,
      blockKey: 'event_' + info.key,
      docId: info.docId,
      desc: 'EVENT_' + info.key.toUpperCase() + '_DESC',
      code: info.code ?? 'on ' + info.key.replace(/_/g, ' '),
      eventValues: info.eventValues,
      cancellable: info.cancellable,
    })
  })
}
