'skript syntax'

import * as Blockly from 'blockly/core'
import { registerSimpleEvent } from './SkriptEventBlock'

type SimpleEventInfo = {
  key: string
  code?: string
  event_values?: string[]
  cancellable: boolean
  docId?: number
}

const SimpleEventInfos: SimpleEventInfo[] = [
  { key: 'can build check', event_values: [], cancellable: false },
  { key: 'block damage', event_values: [], cancellable: false },
  { key: 'flow', event_values: [], cancellable: false },
  { key: 'ignition', event_values: [], cancellable: false },
  { key: 'physics', event_values: [], cancellable: false },
  { key: 'piston extend', event_values: [], cancellable: false },
  { key: 'piston retract', event_values: [], cancellable: false },
  { key: 'redstone', event_values: [], cancellable: false },
  { key: 'spread', event_values: [], cancellable: false },
  { key: 'chunk load', event_values: [], cancellable: false },
  { key: 'chunk generate', event_values: [], cancellable: false },
  { key: 'chunk unload', event_values: [], cancellable: false },
  { key: 'creeper power', event_values: [], cancellable: false },
  { key: 'zombie break door', event_values: [], cancellable: false },
  { key: 'combust', event_values: [], cancellable: false },
  { key: 'explode', event_values: [], cancellable: false },
  { key: 'portal enter', event_values: [], cancellable: false },
  { key: 'tame', event_values: [], cancellable: false },
  { key: 'explosion prime', event_values: [], cancellable: false },
  { key: 'hunger meter change', event_values: [], cancellable: false },
  { key: 'leaves decay', event_values: [], cancellable: false },
  { key: 'lightning strike', event_values: [], cancellable: false },
  { key: 'pig zap', event_values: [], cancellable: false },
  { key: 'bed enter', event_values: [], cancellable: false },
  { key: 'bed leave', event_values: [], cancellable: false },
  { key: 'bucket empty', event_values: [], cancellable: false },
  { key: 'bucket fill', event_values: [], cancellable: false },
  { key: 'egg throw', event_values: [], cancellable: false },
  { key: 'item break', code: 'tool break', event_values: [], cancellable: false },
  { key: 'item damage', event_values: [], cancellable: false },
  { key: 'tool change', event_values: [], cancellable: false },
  { key: 'join', event_values: [], cancellable: false },
  { key: 'connect', event_values: [], cancellable: false },
  { key: 'kick', event_values: [], cancellable: false },
  { key: 'quit', event_values: [], cancellable: false },
  { key: 'respawn', event_values: [], cancellable: false },
  { key: 'sneak toggle', event_values: [], cancellable: false },
  { key: 'sprint toggle', event_values: [], cancellable: false },
  { key: 'portal create', event_values: [], cancellable: false },
  { key: 'projectile hit', event_values: [], cancellable: false },
  { key: 'projectile collide', event_values: [], cancellable: false },
  { key: 'shoot', event_values: [], cancellable: false },
  { key: 'sign change', event_values: [], cancellable: false },
  { key: 'spawn change', event_values: [], cancellable: false },
  { key: 'vehicle create', event_values: [], cancellable: false },
  { key: 'vehicle damage', event_values: [], cancellable: false },
  { key: 'vehicle destroy', event_values: [], cancellable: false },
  { key: 'vehicle enter', event_values: [], cancellable: false },
  { key: 'vehicle exit', event_values: [], cancellable: false },
  { key: 'entity mount', code: 'mount', event_values: [], cancellable: false },
  { key: 'entity dismount', code: 'dismount', event_values: [], cancellable: false },
  { key: 'gliding state change', event_values: [], cancellable: false },
  { key: 'aoe cloud effect', code: 'area cloud effect', event_values: [], cancellable: false },
  { key: 'sheep regrow wool', event_values: [], cancellable: false },
  { key: 'inventory open', event_values: [], cancellable: false },
  { key: 'inventory close', event_values: [], cancellable: false },
  { key: 'slime split', event_values: [], cancellable: false },
  { key: 'resurrect attempt', event_values: [], cancellable: false },
  { key: 'player world change', event_values: [], cancellable: false },
  { key: 'flight toggle', event_values: [], cancellable: false },
  { key: 'language change', event_values: [], cancellable: false },
  { key: 'jump', event_values: [], cancellable: false },
  { key: 'hand item swap', code: 'swap hand items', event_values: [], cancellable: false },
  { key: 'server list ping', event_values: [], cancellable: false },
  { key: 'swim toggle', event_values: [], cancellable: false },
  { key: 'riptide', event_values: [], cancellable: false },
  { key: 'sponge absorb', event_values: [], cancellable: false },
  { key: 'enchant prepare', event_values: [], cancellable: false },
  { key: 'enchant', event_values: [], cancellable: false },
  { key: 'inventory pickup', event_values: [], cancellable: false },
  { key: 'horse jump', event_values: [], cancellable: false },
  { key: 'block fertilize', event_values: [], cancellable: false },
  { key: 'arm swing', event_values: [], cancellable: false },
  { key: 'item mend', event_values: [], cancellable: false },
  { key: 'anvil prepare', event_values: [], cancellable: false },
  { key: 'player trade', event_values: [], cancellable: false },
  { key: 'entity jump', event_values: [], cancellable: false },
  { key: 'anvil damage', event_values: [], cancellable: false },
  { key: 'stop using item', event_values: [], cancellable: false },
  { key: 'ready arrow', event_values: [], cancellable: false },
  { key: 'inventory slot change', event_values: [], cancellable: false },
  { key: 'player deep sleep', event_values: [], cancellable: false },
  { key: 'player pickup arrow', event_values: [], cancellable: false },
  { key: 'inventory drag', event_values: [], cancellable: false },
  { key: 'piglin barter', event_values: [], cancellable: false },
  { key: 'bell ring', event_values: [], cancellable: false },
  { key: 'bell resonate', event_values: [], cancellable: false },
  { key: 'enderman enrage', event_values: [], cancellable: false },
  { key: 'beacon change effect', event_values: [], cancellable: false },
  { key: 'broadcast', event_values: [], cancellable: false },
  { key: 'experience cooldown change', event_values: [], cancellable: false },
  { key: 'vehicle move', event_values: [], cancellable: false },
  { key: 'elytra boost', event_values: [], cancellable: false },
  { key: 'bat toggle sleep', event_values: [], cancellable: false },
  { key: 'world border bounds change', event_values: [], cancellable: false },
  { key: 'world border bounds finish change', event_values: [], cancellable: false },
  { key: 'world border center change', event_values: [], cancellable: false },
  { key: 'vault display item', event_values: [], cancellable: false },
  { key: 'villager career change', event_values: [], cancellable: false },
]

export function registerAll(): Blockly.utils.toolbox.BlockInfo[] {
  return SimpleEventInfos.map((info) => {
    return registerSimpleEvent({
      title: info.key,
      blockKey: 'event_' + info.key.replace(' ', '_'),
      docId: info.docId ?? 0,
      desc: 'EVENT_' + info.key + '_DESC',
      code: info.code ?? 'on ' + info.key,
      eventValues: info.event_values ?? [],
      cancellable: info.cancellable,
    })
  })
}
