import * as Blockly from 'blockly/core'

export class SkriptCodeGenerator extends Blockly.Generator {
  constructor() {
    super('Skript')
    this.INDENT = '    '
  }

  init(_workspace: Blockly.Workspace): void {
    super.init(_workspace)

    if (this.nameDB_) {
      this.nameDB_.reset()
    } else {
      this.nameDB_ = new Blockly.Names(this.RESERVED_WORDS_)
    }

    this.nameDB_.setVariableMap(_workspace.getVariableMap())
    this.nameDB_.populateVariables(_workspace)
    this.nameDB_.populateProcedures(_workspace)

    this.isInitialized = true
  }

  public workspaceToCode(workspace?: Blockly.Workspace): string {
    const code = super.workspaceToCode(workspace)
    const generateInfo = `# Generated by SkriptBlockly © 2026 SuperKripts
# Online Website: https://superkripts.github.io/blockly/
# Github: https://github.com/SuperKripts/skript-blockly/
# Generated on ${new Date().toLocaleString()}

`
    if (workspace) {
      const topComments = workspace.getTopComments()
      if (topComments.length > 0) {
        const sortedComments = topComments
          .map((comment) => {
            const { x, y } = comment.getRelativeToSurfaceXY()
            return { text: comment.getText(), x, y }
          })
          .sort((a, b) => {
            if (a.y !== b.y) return a.y - b.y
            return a.x - b.x
          })

        const commentLines = sortedComments
          .flatMap((item) => item.text.split('\n'))
          .map((line) => '# ' + line)
          .join('\n')

        return generateInfo + commentLines + '\n\n' + code
      }
    }
    return generateInfo + code
  }

  public scrub_(_block: Blockly.Block, code: string, _opt_thisOnly?: boolean | undefined): string {
    let comments = _block.getCommentText() ?? ''
    if (comments != '') {
      comments =
        comments
          .split('\n')
          .map((s) => '# ' + s)
          .join('\n') + '\n'
    }
    const nextBlock = _block.nextConnection?.targetBlock()
    if (nextBlock && !_opt_thisOnly) {
      return comments + code + '\n' + this.blockToCode(nextBlock) + '\n'
    }
    return comments + code
  }

  static codeJoin(...codes: (string | (string | undefined)[])[]): string {
    return codes
      .map((e) => {
        if (typeof e === 'string') {
          return e
        }
        return e.map((s) => s ?? '').includes('') ? '' : e.join(' ')
      })
      .filter((e) => e !== '')
      .join(' ')
  }

  static arrayJoin(codes: string[], quote = false): string {
    if (codes.length == 0) {
      return ''
    }
    if (codes.length == 1) {
      return quote ? `"${codes[0]}"` : codes[0]
    }

    const lastIndex = codes.length - 1
    const rest = codes.slice(0, lastIndex)
    const lastElement = codes[lastIndex]

    const restPart = quote ? rest.map((s) => `"${s}"`).join(', ') : rest.join(', ')
    const lastPart = quote ? `"${lastElement}"` : lastElement

    return `${restPart} and ${lastPart}`
  }

  codeJoin(...codes: (string | (string | undefined)[])[]): string {
    return SkriptCodeGenerator.codeJoin(...codes)
  }

  arrayJoin(codes: string[], quote = false): string {
    return SkriptCodeGenerator.arrayJoin(codes, quote)
  }
}

export const generator = new SkriptCodeGenerator()

export default generator

export const Order = {
  ATOMIC: 0,
  TYPE: 0,
  EXPRESSION: 1,
  EFFECT: 2,
  NONE: 99,
}
