name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install #
      - run: npm run build

      - name: Publish
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.MSG_DW_TOKEN }}@github.com/SuperKripts/superkripts.github.io.git
          TARGET_BRANCH: master
          TARGET_SUBFOLDER: blockly
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --depth 1 $TARGET_REPO_URL target-repo
          cd target-repo
          git checkout $TARGET_BRANCH || git checkout -b $TARGET_BRANCH
          mkdir -p $TARGET_SUBFOLDER
          cp -r ../dist/* $TARGET_SUBFOLDER/
          git add $TARGET_SUBFOLDER
          git commit -m "auto deploy from ${{ github.sha }}" || true
          git push origin $TARGET_BRANCH
